# Data Selection and Cleaning

## 1. Loading the Data
The required Python libraries were imported and the 5 datasets were loaded into the notebook.

In [295]:
import pandas as pd
import numpy as np
from functools import reduce

In [296]:
# 1. 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

- The datasets cover different dimensions of the "Sustainable Living Quality Index", including economic, health and education, infrastructure, environment, and governance.
- The missing value symbol `..` was treated as a missing value.

In [297]:
economic_data = pd.read_csv("../Dataset/economic_indicators.csv", na_values=[".."])
infrastructure_data = pd.read_csv('../Dataset/infrastructure_indicators.csv', na_values=[".."])
environmental_data = pd.read_csv('../Dataset/environment_indicators.csv', na_values=[".."])
health_education_data = pd.read_csv('../Dataset/health_education_indicators.csv', na_values=[".."])
governance_data = pd.read_csv('../Dataset/governance_indicators.csv', na_values=[".."])

- After loading the datasets, the shape of each dataset was checked.

In [298]:
print("Economic:", economic_data.shape)
print("Health and Education:", health_education_data.shape)
print("Infrastructure:", infrastructure_data.shape)
print("Environment:", environmental_data.shape)
print("Governance:", governance_data.shape)

Economic: (656, 10)
Health and Education: (656, 10)
Infrastructure: (656, 10)
Environment: (656, 10)
Governance: (653, 9)

## 2. Choosing Relevant Variables
relevant variables were selected from each dataset. The variables were grouped into five main dimensions:
- Economic conditions
- Health and education
- Infrastructure and basic services
- Environmental sustainability
- Governance and stability

Not all variables were selected, and only the most recent data were used.

### Economic

In [299]:
# 1. Define indicators to keep
economic_selected = economic_data[['Country Name', 'Country Code', 'Series Name','2020 [YR2020]','2021 [YR2021]','2022 [YR2022]','2023 [YR2023]','2024 [YR2024]']].copy()

# Keep only selected variables
economic_selected = economic_selected[
    economic_selected['Series Name'].isin([
        'GDP per capita (current US$)',
        'Inflation, consumer prices (annual %)',
        'Unemployment, total (% of total labor force) (modeled ILO estimate)'
    ])
].copy()

# Convert values to numeric
year_columns = ['2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]', '2024 [YR2024]']
for col in year_columns:
    economic_selected[col] = pd.to_numeric(economic_selected[col], errors='coerce')

# Use 2024 first, if missing use 2023
economic_selected['selected_value'] = (economic_selected['2024 [YR2024]']
    .fillna(economic_selected['2023 [YR2023]'])
    .fillna(economic_selected['2022 [YR2022]'])
    .fillna(economic_selected['2021 [YR2021]'])
    .fillna(economic_selected['2020 [YR2020]'])
)

# Convert to wide format
economic_final = economic_selected.pivot_table(
    index=['Country Name', 'Country Code'],
    columns='Series Name',
    values='selected_value',
    aggfunc='first'
).reset_index()

# Rename columns
economic_final = economic_final.rename(columns={
    'Country Name': 'Country',
    'GDP per capita (current US$)': 'gdp_per_capita_recent',
    'Inflation, consumer prices (annual %)': 'inflation_recent',
    'Unemployment, total (% of total labor force) (modeled ILO estimate)': 'unemployment_recent'
})

economic_final.columns.name = None

print(economic_final.shape)
economic_final.head(211)

(215, 5)

,Country,Country Code,gdp_per_capita_recent,inflation_recent,unemployment_recent
0,Afghanistan,AFG,413.757895,-6.601186,13.687
1,Albania,ALB,11377.775743,2.215874,10.689
2,Algeria,DZA,5752.990767,4.046115,11.655
3,American Samoa,ASM,18017.458938,NaN,NaN
4,Andorra,AND,49303.649167,NaN,NaN
5,Angola,AGO,2665.874448,28.240495,14.020
6,Antigua and Barbuda,ATG,23542.452695,6.198867,NaN
7,Argentina,ARG,13969.783660,219.883929,7.150
8,Armenia,ARM,8556.214070,0.269512,12.405
9,Aruba,ABW,39498.594129,NaN,NaN
10,Australia,AUS,64603.985631,3.166567,3.942
11,Austria,AUT,58268.878765,2.937916,5.200
12,Azerbaijan,AZE,7283.849908,2.212172,5.648
13,"Bahamas, The",BHS,39455.446655,0.409162,9.049
14,Bahrain,BHR,29653.568273,0.919635,1.084
15,Bangladesh,BGD,2593.416117,10.465748,3.635
16,Barbados,BRB,26544.870728,1.446437,6.448
17,Belarus,BLR,8317.633999,5.785319,3.458
18,Belgium,BEL,56614.567950,3.143491,5.700
19,Belize,BLZ,7681.244006,3.289560,8.698
20,Benin,BEN,1485.380189,1.160931,1.637
21,Bermuda,BMU,142855.374714,NaN,NaN
22,Bhutan,BTN,3831.325355,2.761316,3.282
23,Bolivia,BOL,4421.166099,5.099766,3.274
24,Bosnia and Herzegovina,BIH,9358.787690,1.692127,10.690
25,Botswana,BWA,7695.753194,2.818351,23.810
26,Brazil,BRA,10310.548878,4.367464,6.801
27,Brunei Darussalam,BRN,33153.473891,-0.388674,5.180
28,Bulgaria,BGR,17596.017366,2.446519,4.200
29,Burkina Faso,BFA,981.992650,4.190817,3.441
30,Burundi,BDI,219.424831,20.212493,0.915
31,Cabo Verde,CPV,5192.481573,1.048170,11.883
32,Cambodia,KHM,2627.879698,0.808042,0.254
33,Cameroon,CMR,1830.008337,4.533313,3.603
34,Canada,CAN,54340.347722,2.381584,6.351
35,Cayman Islands,CYM,99143.518024,NaN,NaN
36,Central African Republic,CAF,516.161000,1.477336,6.253
37,Chad,TCD,961.559756,8.899507,1.053
38,Channel Islands,CHI,74585.522410,NaN,6.031
39,Chile,CHL,16709.889397,4.297639,8.718
40,China,CHN,13303.148154,0.218129,4.590
41,Colombia,COL,7919.208868,6.609086,9.619
42,Comoros,COM,1662.756633,5.051926,3.815
43,"Congo, Dem. Rep.",COD,649.383339,NaN,4.421
44,"Congo, Rep.",COG,2482.248995,3.091436,19.895
45,Costa Rica,CRI,18587.153220,-0.412853,6.936
46,Cote d'Ivoire,CIV,2727.893522,3.450530,2.273
47,Croatia,HRV,24050.439793,2.972005,5.000
48,Cuba,CUB,9605.279146,NaN,1.755
49,Curacao,CUW,22832.895396,NaN,NaN
50,Cyprus,CYP,38674.292969,1.800230,4.900
51,Czechia,CZE,31823.307829,2.435312,2.600
52,Denmark,DNK,71026.483227,1.372200,5.358
53,Djibouti,DJI,3552.723351,2.112012,26.007
54,Dominica,DMA,10405.278778,2.569219,NaN
55,Dominican Republic,DOM,10875.661844,3.302233,5.312
56,Ecuador,ECU,6874.705740,1.547325,3.453
57,"Egypt, Arab Rep.",EGY,3338.473714,28.270590,6.817
58,El Salvador,SLV,5579.659692,0.853782,3.261
59,Equatorial Guinea,GNQ,6745.400132,2.921402,8.293
60,Eritrea,ERI,NaN,NaN,5.947
61,Estonia,EST,31428.354782,3.519412,7.600
62,Eswatini,SWZ,3909.558924,NaN,34.643
63,Ethiopia,ETH,1133.882797,21.037746,3.357
64,Faroe Islands,FRO,74119.660755,NaN,NaN
65,Fiji,FJI,6425.741517,3.890842,5.361
66,Finland,FIN,53149.767193,1.565689,8.400
67,France,FRA,46103.084086,1.999049,7.400
68,French Polynesia,PYF,22439.883875,NaN,11.613
69,Gabon,GAB,8230.043115,1.173120,20.091
70,"Gambia, The",GMB,871.340292,11.561053,6.480
71,Georgia,GEO,9241.491223,1.109718,11.557
72,Germany,DEU,56103.732318,2.256498,3.400
73,Ghana,GHA,2390.772377,22.848328,2.820
74,Greece,GRC,24626.148186,2.741019,10.020
75,Greenland,GRL,58498.970797,NaN,NaN
76,Grenada,GRD,11705.090298,1.086154,NaN
77,Guam,GUM,41833.151713,NaN,5.252
78,Guatemala,GTM,6150.025714,2.869928,2.613
79,Guinea,GIN,1694.953759,8.123139,5.132
80,Guinea-Bissau,GNB,1007.741517,3.765558,2.647
81,Guyana,GUY,29675.244387,2.903952,11.874
82,Haiti,HTI,2142.623305,26.949056,14.609
83,Honduras,HND,3426.434833,4.606211,4.910
84,"Hong Kong SAR, China",HKG,54074.692852,1.729721,2.988
85,Hungary,HUN,23292.326388,3.703704,4.500
86,Iceland,ISL,86040.530985,5.856838,3.600
87,India,IND,2694.737809,4.953036,4.173
88,Indonesia,IDN,4925.430488,2.181513,3.301
89,"Iran, Islamic Rep.",IRN,5190.169590,32.455871,8.146
90,Iraq,IRQ,6073.610323,-12.296984,15.293
91,Ireland,IRL,112894.953241,2.113450,4.300
92,Isle of Man,IMN,88328.548126,NaN,NaN
93,Israel,ISR,54176.684438,3.074809,3.595
94,Italy,ITA,40385.341396,0.982373,6.500
95,Jamaica,JAM,7753.800696,5.411944,3.151
96,Japan,JPN,32487.077805,2.738537,2.500
97,Jordan,JOR,4618.095925,1.556596,16.693
98,Kazakhstan,KAZ,14154.632496,8.690822,4.833
99,Kenya,KEN,2132.434521,4.489789,5.487
100,Kiribati,KIR,2288.634714,2.455451,NaN
101,"Korea, Dem. People's Rep.",PRK,NaN,NaN,3.539
102,"Korea, Rep.",KOR,36238.639908,2.321743,2.784
103,Kosovo,XKX,7023.065985,1.619450,NaN
104,Kuwait,KWT,32717.718663,2.898551,2.151
105,Kyrgyz Republic,KGZ,2420.185423,4.997607,3.491
106,Lao PDR,LAO,2123.979094,23.130570,1.174
107,Latvia,LVA,23409.084515,1.265799,6.900
108,Lebanon,LBN,3477.724898,45.243042,10.985
109,Lesotho,LSO,971.907718,6.105446,16.340
110,Liberia,LBR,851.497724,8.214974,2.914
111,Libya,LBY,6569.164087,2.126158,19.085
112,Liechtenstein,LIE,206780.590353,NaN,NaN
113,Lithuania,LTU,29384.018960,0.715736,6.851
114,Luxembourg,LUX,137781.681659,2.051133,6.400
115,"Macao SAR, China",MAC,72004.743702,0.672499,2.262
116,Madagascar,MDG,544.987501,7.613358,3.051
117,Malawi,MWI,522.570394,32.179650,5.051
118,Malaysia,MYS,11874.427368,1.834100,3.846
119,Maldives,MDV,13379.351358,1.399798,4.278
120,Mali,MLI,1094.619493,3.206399,2.924
121,Malta,MLT,43898.578181,1.650795,3.100
122,Marshall Islands,MHL,7726.336689,NaN,NaN
123,Mauritania,MRT,2110.120369,2.491643,10.257
124,Mauritius,MUS,11990.779894,3.604522,5.548
125,Mexico,MEX,14185.781225,4.722256,2.678
126,"Micronesia, Fed. Sts.",FSM,4166.004767,5.408744,NaN
127,Moldova,MDA,7576.195894,4.677735,1.427
128,Monaco,MCO,288001.433369,NaN,NaN
129,Mongolia,MNG,6750.630116,6.197799,5.158
130,Montenegro,MNE,13263.328128,3.336750,13.206
131,Morocco,MAR,4153.194336,0.985257,9.103
132,Mozambique,MOZ,656.776825,4.078568,6.668
133,Myanmar,MMR,1359.050016,NaN,2.887
134,Namibia,NAM,4413.127522,4.239039,19.157
135,Nauru,NRU,13609.158838,NaN,NaN
136,Nepal,NPL,1447.310045,4.685097,10.500
137,Netherlands,NLD,67520.421896,3.347543,3.700
138,New Caledonia,NCL,29213.192319,NaN,10.991
139,New Zealand,NZL,49205.179215,2.922798,4.724
140,Nicaragua,NIC,2847.539663,4.624738,4.980
141,Niger,NER,735.270256,9.071520,0.376
142,Nigeria,NGA,1084.160418,33.242097,3.045
143,North Macedonia,MKD,9291.856617,3.489741,12.265
144,Northern Mariana Islands,MNP,23785.754590,NaN,NaN
145,Norway,NOR,86785.433449,3.145301,4.000
146,Oman,OMN,20285.227290,0.593589,3.203
147,Pakistan,PAK,1478.772780,12.632532,5.492
148,Palau,PLW,15610.823193,2.231728,NaN
149,Panama,PAN,19161.218850,0.693226,8.451
150,Papua New Guinea,PNG,3006.705645,0.602404,2.625
151,Paraguay,PRY,6416.097090,3.835403,5.686
152,Peru,PER,8452.371671,2.007707,5.199
153,Philippines,PHL,3984.831539,3.212605,2.202
154,Poland,POL,25103.565661,3.790609,2.807
155,Portugal,PRT,29292.242105,2.416132,6.500
156,Puerto Rico (US),PRI,39343.715466,NaN,5.639
157,Qatar,QAT,76688.694174,1.267343,0.130
158,Romania,ROU,20080.209622,5.721406,5.400
159,Russian Federation,RUS,14889.018555,8.434864,2.430
160,Rwanda,RWA,999.654562,1.770292,11.331
161,Samoa,WSM,5392.877619,2.172455,4.855
162,San Marino,SMR,59879.717302,1.242165,NaN
163,Sao Tome and Principe,STP,3490.568835,14.351927,9.057
164,Saudi Arabia,SAU,35121.662869,1.687921,3.518
165,Senegal,SEN,1773.218299,0.804503,2.788
166,Serbia,SRB,13679.206598,4.670530,7.240
167,Seychelles,SYC,17858.822638,0.311726,NaN
168,Sierra Leone,SLE,806.654650,28.633750,3.103
169,Singapore,SGP,90674.066633,2.389511,2.737
170,Sint Maarten (Dutch part),SXM,41472.587450,NaN,NaN
171,Slovak Republic,SVK,25992.674850,2.757609,5.300
172,Slovenia,SVN,34301.031869,1.965627,3.700
173,Solomon Islands,SLB,1933.555384,4.321839,1.444
174,"Somalia, Fed. Rep.",SOM,629.538899,NaN,18.949
175,South Africa,ZAF,6267.186814,4.361152,32.279
176,South Sudan,SSD,NaN,91.440822,12.374
177,Spain,ESP,35326.768307,2.774178,11.400
178,Sri Lanka,LKA,4515.567873,-0.429360,4.239
179,St. Kitts and Nevis,KNA,23960.653436,3.557112,NaN
180,St. Lucia,LCA,14181.630335,-0.110284,10.199
181,St. Martin (French part),MAF,21668.377653,NaN,NaN
182,St. Vincent and the Grenadines,VCT,11501.226519,3.627707,18.093
183,Sudan,SDN,984.607666,138.808460,7.530
184,Suriname,SUR,6961.789560,16.229616,7.621
185,Sweden,SWE,57117.487744,2.835817,8.400
186,Switzerland,CHE,103998.186686,1.062340,4.343
187,Syrian Arab Republic,SYR,1051.671496,NaN,13.359
188,Tajikistan,TJK,1341.202290,NaN,7.041
189,Tanzania,TZA,1186.716919,3.056947,1.557
190,Thailand,THA,7346.620221,1.365805,0.781
191,Timor-Leste,TLS,1331.970513,2.062842,1.523
192,Togo,TGO,1119.381605,2.862621,1.948
193,Tonga,TON,5651.593731,3.230563,1.965
194,Trinidad and Tobago,TTO,18733.411041,0.526885,3.318
195,Tunisia,TUN,4181.137893,7.206617,15.341
196,Turkiye,TUR,15892.715729,58.506451,8.800
197,Turkmenistan,TKM,6856.658027,NaN,4.020
198,Turks and Caicos Islands,TCA,37506.779843,NaN,NaN
199,Tuvalu,TUV,6344.775019,NaN,NaN
200,Uganda,UGA,1077.912785,3.323381,2.740
201,Ukraine,UKR,5389.473145,6.501985,9.834
202,United Arab Emirates,ARE,50273.506047,1.663365,2.160
203,United Kingdom,GBR,53246.367615,3.271573,4.361
204,United States,USA,84534.040784,2.949525,4.022
205,Uruguay,URY,23906.513303,4.849144,8.209
206,Uzbekistan,UZB,3161.700106,9.628255,4.439
207,Vanuatu,VUT,3410.770232,11.182502,4.988
208,"Venezuela, RB",VEN,4217.591026,NaN,5.321
209,Viet Nam,VNM,4717.290287,3.621093,1.602
210,Virgin Islands (U.S.),VIR,44320.909186,NaN,11.423

- 2024 was used as the reference year. Where 2024 values were missing, 2023 values were used as a one-year backfill.

### Health and Education

In [300]:
health_education_selected = health_education_data[['Country Name', 'Country Code', 'Series Name','2020 [YR2020]','2021 [YR2021]','2022 [YR2022]','2023 [YR2023]','2024 [YR2024]']].copy()

health_education_selected = health_education_selected[
    health_education_selected['Series Name'].isin([
        'Life expectancy at birth, total (years)',
        'School enrollment, secondary (% gross)',
    ])
].copy()

# Convert values to numeric
year_columns = ['2020 [YR2020]','2021 [YR2021]','2022 [YR2022]','2023 [YR2023]','2024 [YR2024]']

for col in year_columns:
    health_education_selected[col] = pd.to_numeric(
        health_education_selected[col],
        errors='coerce'
    )

# Create selected value column
health_education_selected['selected_value'] = np.nan

# Life expectancy: use 2024 first, if missing use 2023
life_mask = health_education_selected['Series Name'] == 'Life expectancy at birth, total (years)'
health_education_selected.loc[life_mask, 'selected_value'] = (
    health_education_selected.loc[life_mask, '2024 [YR2024]']
    .fillna(health_education_selected.loc[life_mask, '2023 [YR2023]'])
)

# Secondary enrollment: latest available from 2024 to 2020
secondary_mask = health_education_selected['Series Name'] == 'School enrollment, secondary (% gross)'
health_education_selected.loc[secondary_mask, 'selected_value'] = (
    health_education_selected.loc[secondary_mask, '2024 [YR2024]']
    .fillna(health_education_selected.loc[secondary_mask, '2023 [YR2023]'])
    .fillna(health_education_selected.loc[secondary_mask, '2022 [YR2022]'])
    .fillna(health_education_selected.loc[secondary_mask, '2021 [YR2021]'])
    .fillna(health_education_selected.loc[secondary_mask, '2020 [YR2020]'])
)

# Pivot to wide format
health_education_final = health_education_selected.pivot_table(
    index=['Country Name', 'Country Code'],
    columns='Series Name',
    values='selected_value',
    aggfunc='first'
).reset_index()

health_education_final = health_education_final.rename(columns={
    'Country Name': 'Country',
    'Life expectancy at birth, total (years)': 'life_expectancy_2024',
    'School enrollment, secondary (% gross)': 'secondary_enrollment_recent',
})

health_education_final.columns.name = None

print(health_education_final.shape)
health_education_final.head(217)

(217, 4)

,Country,Country Code,life_expectancy_2024,secondary_enrollment_recent
0,Afghanistan,AFG,66.289000,59.613602
1,Albania,ALB,79.776000,108.355392
2,Algeria,DZA,76.475000,105.164132
3,American Samoa,ASM,72.992000,NaN
4,Andorra,AND,84.188000,101.923820
5,Angola,AGO,64.805000,51.483905
6,Antigua and Barbuda,ATG,77.766000,108.880779
7,Argentina,ARG,77.543000,105.574584
8,Armenia,ARM,78.319512,90.945871
9,Aruba,ABW,76.500000,124.379367
10,Australia,AUS,83.051220,131.931564
11,Austria,AUT,81.995122,100.622658
12,Azerbaijan,AZE,74.576000,91.122804
13,"Bahamas, The",BHS,74.710000,79.485875
14,Bahrain,BHR,81.423000,98.813918
15,Bangladesh,BGD,74.930000,64.299719
16,Barbados,BRB,76.332000,104.371183
17,Belarus,BLR,74.365341,94.790270
18,Belgium,BEL,82.300000,142.960266
19,Belize,BLZ,73.739000,86.457158
20,Benin,BEN,60.961000,43.560650
21,Bermuda,BMU,82.490000,74.396751
22,Bhutan,BTN,73.262000,86.181000
23,Bolivia,BOL,68.739000,90.527222
24,Bosnia and Herzegovina,BIH,78.044000,87.866379
25,Botswana,BWA,69.293000,70.629257
26,Brazil,BRA,76.023000,104.144661
27,British Virgin Islands,VGB,77.431000,75.583313
28,Brunei Darussalam,BRN,75.501000,91.838154
29,Bulgaria,BGR,75.760976,94.781631
30,Burkina Faso,BFA,61.292000,29.990577
31,Burundi,BDI,63.818000,44.915172
32,Cabo Verde,CPV,76.224000,96.431594
33,Cambodia,KHM,70.817000,58.789323
34,Cameroon,CMR,63.968000,44.840796
35,Canada,CAN,82.108049,104.320877
36,Cayman Islands,CYM,80.540000,84.760310
37,Central African Republic,CAF,57.671000,NaN
38,Chad,TCD,55.238000,23.492989
39,Channel Islands,CHI,81.200000,NaN
40,Chile,CHL,81.359000,105.608551
41,China,CHN,78.017000,NaN
42,Colombia,COL,77.913000,101.573776
43,Comoros,COM,67.023000,54.805729
44,"Congo, Dem. Rep.",COD,62.074000,55.486099
45,"Congo, Rep.",COG,66.001000,NaN
46,Costa Rica,CRI,80.996000,121.810760
47,Cote d'Ivoire,CIV,62.110000,65.306506
48,Croatia,HRV,78.929268,105.025162
49,Cuba,CUB,78.264000,91.745684
50,Curacao,CUW,76.989000,89.905342
51,Cyprus,CYP,81.821000,106.741280
52,Czechia,CZE,79.978049,97.615417
53,Denmark,DNK,82.253659,125.628090
54,Djibouti,DJI,66.202000,NaN
55,Dominica,DMA,71.294000,102.585808
56,Dominican Republic,DOM,73.868000,76.364840
57,Ecuador,ECU,77.579000,92.811803
58,"Egypt, Arab Rep.",EGY,71.806000,84.828603
59,El Salvador,SLV,72.302000,62.142585
60,Equatorial Guinea,GNQ,63.906000,NaN
61,Eritrea,ERI,68.893000,44.044128
62,Estonia,EST,79.295122,108.538727
63,Eswatini,SWZ,64.264000,NaN
64,Ethiopia,ETH,67.603000,NaN
65,Faroe Islands,FRO,83.083246,NaN
66,Fiji,FJI,67.463000,98.092763
67,Finland,FIN,82.336585,142.395157
68,France,FRA,82.980488,103.785408
69,French Polynesia,PYF,84.192000,NaN
70,Gabon,GAB,68.511000,NaN
71,"Gambia, The",GMB,66.057000,107.027126
72,Georgia,GEO,74.657000,100.959316
73,Germany,DEU,80.792683,100.243698
74,Ghana,GHA,65.695000,75.717468
75,Gibraltar,GIB,83.630000,78.527977
76,Greece,GRC,81.839024,105.191742
77,Greenland,GRL,70.273415,NaN
78,Grenada,GRD,75.367000,100.731679
79,Guam,GUM,77.422000,NaN
80,Guatemala,GTM,72.746000,49.576580
81,Guinea,GIN,60.904000,NaN
82,Guinea-Bissau,GNB,64.254000,NaN
83,Guyana,GUY,70.319000,91.430450
84,Haiti,HTI,65.119000,NaN
85,Honduras,HND,73.044000,51.763981
86,"Hong Kong SAR, China",HKG,85.392683,107.160327
87,Hungary,HUN,76.724390,107.350929
88,Iceland,ISL,82.809756,108.911362
89,India,IND,72.235000,78.105807
90,Indonesia,IDN,71.288000,98.836444
91,"Iran, Islamic Rep.",IRN,77.854000,85.146980
92,Iraq,IRQ,72.424000,NaN
93,Ireland,IRL,83.009756,130.604965
94,Isle of Man,IMN,81.091000,NaN
95,Israel,ISR,83.197561,98.547340
96,Italy,ITA,83.951220,100.678757
97,Jamaica,JAM,71.606000,84.457237
98,Japan,JPN,84.036341,101.537071
99,Jordan,JOR,77.981000,91.751862
100,Kazakhstan,KAZ,74.531000,97.198884
101,Kenya,KEN,63.834000,84.308388
102,Kiribati,KIR,66.600000,90.278671
103,"Korea, Dem. People's Rep.",PRK,73.743000,NaN
104,"Korea, Rep.",KOR,83.629268,96.253990
105,Kosovo,XKX,78.222000,NaN
106,Kuwait,KWT,84.580488,NaN
107,Kyrgyz Republic,KGZ,72.400000,91.339996
108,Lao PDR,LAO,69.225000,51.852360
109,Latvia,LVA,76.429268,101.252647
110,Lebanon,LBN,77.945000,63.792301
111,Lesotho,LSO,57.798000,NaN
112,Liberia,LBR,62.324000,37.741680
113,Libya,LBY,71.121000,NaN
114,Liechtenstein,LIE,84.200000,118.726868
115,Lithuania,LTU,77.195122,104.860809
116,Luxembourg,LUX,83.195122,108.577438
117,"Macao SAR, China",MAC,83.331707,94.661677
118,Madagascar,MDG,63.835000,34.132036
119,Malawi,MWI,67.561000,36.644093
120,Malaysia,MYS,76.821000,80.275741
121,Maldives,MDV,81.285000,79.356530
122,Mali,MLI,60.675000,38.938947
123,Malta,MLT,82.956098,103.027229
124,Marshall Islands,MHL,67.075000,85.755864
125,Mauritania,MRT,68.713000,36.027703
126,Mauritius,MUS,73.789024,90.724659
127,Mexico,MEX,75.264000,103.093323
128,"Micronesia, Fed. Sts.",FSM,67.357000,NaN
129,Moldova,MDA,71.332000,99.343917
130,Monaco,MCO,86.497000,158.546616
131,Mongolia,MNG,72.398049,96.818120
132,Montenegro,MNE,77.890244,93.872498
133,Morocco,MAR,75.493000,89.983486
134,Mozambique,MOZ,63.797000,NaN
135,Myanmar,MMR,67.095000,NaN
136,Namibia,NAM,67.516000,81.956683
137,Nauru,NRU,62.279000,91.513352
138,Nepal,NPL,70.636000,90.387846
139,Netherlands,NLD,81.965854,137.514725
140,New Caledonia,NCL,78.921000,NaN
141,New Zealand,NZL,82.009756,114.231056
142,Nicaragua,NIC,75.100000,70.174957
143,Niger,NER,61.433000,19.866476
144,Nigeria,NGA,54.635000,46.893150
145,North Macedonia,MKD,76.616585,90.072487
146,Northern Mariana Islands,MNP,78.947000,NaN
147,Norway,NOR,83.160976,116.254272
148,Oman,OMN,80.246000,95.122040
149,Pakistan,PAK,67.799000,48.280502
150,Palau,PLW,69.383000,95.727085
151,Panama,PAN,79.775000,NaN
152,Papua New Guinea,PNG,66.256000,52.092975
153,Paraguay,PRY,73.982000,79.130561
154,Peru,PER,77.941000,108.289047
155,Philippines,PHL,69.946000,85.294509
156,Poland,POL,78.409756,107.881310
157,Portugal,PRT,82.382927,120.347076
158,Puerto Rico (US),PRI,81.902000,81.482414
159,Qatar,QAT,82.522000,99.578857
160,Romania,ROU,76.458537,81.631607
161,Russian Federation,RUS,73.440488,92.484047
162,Rwanda,RWA,68.017000,48.790277
163,Samoa,WSM,71.826000,NaN
164,San Marino,SMR,85.817000,60.374640
165,Sao Tome and Principe,STP,69.905000,NaN
166,Saudi Arabia,SAU,78.982000,110.663465
167,Senegal,SEN,68.924000,44.067368
168,Serbia,SRB,75.968293,89.840279
169,Seychelles,SYC,76.295122,70.824577
170,Sierra Leone,SLE,61.964000,86.907951
171,Singapore,SGP,83.346341,103.082802
172,Sint Maarten (Dutch part),SXM,76.528000,NaN
173,Slovak Republic,SVK,78.370732,93.192993
174,Slovenia,SVN,82.285366,107.626877
175,Solomon Islands,SLB,70.694000,NaN
176,"Somalia, Fed. Rep.",SOM,58.967000,3.347850
177,South Africa,ZAF,66.312000,104.133481
178,South Sudan,SSD,57.738000,122.120628
179,Spain,ESP,83.887805,118.537804
180,Sri Lanka,LKA,77.672000,87.953407
181,St. Kitts and Nevis,KNA,72.281000,137.513209
182,St. Lucia,LCA,72.846000,87.867242
183,St. Martin (French part),MAF,80.438000,NaN
184,St. Vincent and the Grenadines,VCT,71.382000,124.871795
185,Sudan,SDN,66.521000,NaN
186,Suriname,SUR,73.757000,76.110924
187,Sweden,SWE,84.063415,131.963547
188,Switzerland,CHE,84.407317,101.428711
189,Syrian Arab Republic,SYR,72.560000,38.736931
190,Tajikistan,TJK,71.927000,86.903526
191,Tanzania,TZA,67.212000,28.231331
192,Thailand,THA,76.564000,92.507326
193,Timor-Leste,TLS,67.904000,84.741040
194,Togo,TGO,62.935000,63.419252
195,Tonga,TON,73.070000,92.425805
196,Trinidad and Tobago,TTO,73.617000,95.681565
197,Tunisia,TUN,76.711000,NaN
198,Turkiye,TUR,77.421000,118.411980
199,Turkmenistan,TKM,70.201000,94.646413
200,Turks and Caicos Islands,TCA,78.181000,119.728976
201,Tuvalu,TUV,67.259000,90.657165
202,Uganda,UGA,68.487000,NaN
203,Ukraine,UKR,74.692000,86.169502
204,United Arab Emirates,ARE,83.069000,102.129725
205,United Kingdom,GBR,81.386854,112.120049
206,United States,USA,78.890244,97.473488
207,Uruguay,URY,78.287000,119.105006
208,Uzbekistan,UZB,72.528000,96.839922
209,Vanuatu,VUT,71.654000,134.670675
210,"Venezuela, RB",VEN,72.673000,97.790817
211,Viet Nam,VNM,74.736000,93.412343
212,Virgin Islands (U.S.),VIR,80.770732,NaN
213,West Bank and Gaza,PSE,69.213000,89.121098
214,"Yemen, Rep.",YEM,69.439000,NaN
215,Zambia,ZMB,66.528000,56.788929
216,Zimbabwe,ZWE,63.064000,NaN

### Infrastructure

In [301]:
infrastructure_selected = infrastructure_data[['Country Name', 'Country Code', 'Series Name', '2023 [YR2023]', '2024 [YR2024]']].copy()

infrastructure_selected = infrastructure_selected[
    infrastructure_selected['Series Name'].isin([
        'Access to electricity (% of population)',
        'People using at least basic drinking water services (% of population)',
        'People using at least basic sanitation services (% of population)'
    ])
].copy()

infrastructure_selected['2023 [YR2023]'] = pd.to_numeric(infrastructure_selected['2023 [YR2023]'], errors='coerce')
infrastructure_selected['2024 [YR2024]'] = pd.to_numeric(infrastructure_selected['2024 [YR2024]'], errors='coerce')

infrastructure_selected['selected_value'] = infrastructure_selected['2024 [YR2024]'].fillna(infrastructure_selected['2023 [YR2023]'])

infrastructure_final = infrastructure_selected.pivot_table(
    index=['Country Name', 'Country Code'],
    columns='Series Name',
    values='selected_value',
    aggfunc='first'
).reset_index()

infrastructure_final = infrastructure_final.rename(columns={
    'Country Name': 'Country',
    'Access to electricity (% of population)': 'electricity_access_2024',
    'People using at least basic drinking water services (% of population)': 'drinking_water_access',
    'People using at least basic sanitation services (% of population)': 'sanitation_access'
})

infrastructure_final.columns.name = None

print(infrastructure_final.shape)
infrastructure_final.head(216)

(216, 5)

,Country,Country Code,electricity_access_2024,drinking_water_access,sanitation_access
0,Afghanistan,AFG,85.3,80.832437,54.495799
1,Albania,ALB,100.0,95.119427,99.299715
2,Algeria,DZA,100.0,92.420029,85.906486
3,American Samoa,ASM,NaN,100.000000,62.119698
4,Andorra,AND,100.0,100.000000,100.000000
5,Angola,AGO,51.1,67.960742,NaN
6,Antigua and Barbuda,ATG,100.0,98.922727,99.605719
7,Argentina,ARG,100.0,NaN,NaN
8,Armenia,ARM,100.0,99.931572,93.664943
9,Aruba,ABW,100.0,NaN,98.840002
10,Australia,AUS,100.0,99.969636,100.000000
11,Austria,AUT,100.0,99.999997,99.972102
12,Azerbaijan,AZE,100.0,97.688084,98.978507
13,"Bahamas, The",BHS,100.0,NaN,NaN
14,Bahrain,BHR,100.0,99.919899,100.000000
15,Bangladesh,BGD,99.5,98.782542,67.617175
16,Barbados,BRB,100.0,99.162635,98.092462
17,Belarus,BLR,100.0,99.892492,99.747353
18,Belgium,BEL,100.0,100.000000,99.486221
19,Belize,BLZ,99.6,94.847325,84.301766
20,Benin,BEN,57.0,69.586840,22.248969
21,Bermuda,BMU,100.0,100.000000,99.941653
22,Bhutan,BTN,100.0,99.546579,86.842108
23,Bolivia,BOL,99.8,93.387749,71.583920
24,Bosnia and Herzegovina,BIH,100.0,96.087313,NaN
25,Botswana,BWA,76.0,91.771364,72.115457
26,Brazil,BRA,99.8,99.999999,92.401270
27,British Virgin Islands,VGB,100.0,99.864384,NaN
28,Brunei Darussalam,BRN,100.0,100.000000,100.000000
29,Bulgaria,BGR,100.0,99.185252,86.076561
30,Burkina Faso,BFA,21.7,49.998660,31.796349
31,Burundi,BDI,11.6,65.919104,44.633989
32,Cabo Verde,CPV,98.6,92.280089,83.127922
33,Cambodia,KHM,95.0,82.849757,83.335933
34,Cameroon,CMR,72.0,71.410179,47.072948
35,Canada,CAN,100.0,98.290261,98.587883
36,Cayman Islands,CYM,100.0,95.460123,83.244217
37,Central African Republic,CAF,17.6,36.504027,14.036284
38,Chad,TCD,12.0,52.209053,13.141529
39,Channel Islands,CHI,100.0,NaN,NaN
40,Chile,CHL,100.0,99.081161,99.999996
41,China,CHN,100.0,96.122415,97.271879
42,Colombia,COL,98.7,97.096571,96.582015
43,Comoros,COM,89.8,85.053928,57.223089
44,"Congo, Dem. Rep.",COD,22.1,35.681361,16.303312
45,"Congo, Rep.",COG,51.3,NaN,NaN
46,Costa Rica,CRI,100.0,99.815412,98.788841
47,Cote d'Ivoire,CIV,72.4,77.247059,40.407069
48,Croatia,HRV,100.0,99.903181,NaN
49,Cuba,CUB,100.0,95.146406,94.770351
50,Curacao,CUW,100.0,100.000000,NaN
51,Cyprus,CYP,100.0,99.721109,99.477676
52,Czechia,CZE,100.0,98.734148,99.070054
53,Denmark,DNK,100.0,100.000000,99.597226
54,Djibouti,DJI,65.2,79.661533,67.023484
55,Dominica,DMA,100.0,96.995311,NaN
56,Dominican Republic,DOM,99.6,97.457130,90.119824
57,Ecuador,ECU,98.7,92.070871,91.204340
58,"Egypt, Arab Rep.",EGY,100.0,97.298243,97.086129
59,El Salvador,SLV,98.3,91.619993,88.041116
60,Equatorial Guinea,GNQ,66.9,NaN,NaN
61,Eritrea,ERI,54.4,NaN,NaN
62,Estonia,EST,100.0,99.999997,99.021494
63,Eswatini,SWZ,86.4,80.373711,64.460503
64,Ethiopia,ETH,55.4,55.596070,10.357719
65,Faroe Islands,FRO,100.0,100.000000,NaN
66,Fiji,FJI,99.3,95.560390,92.754290
67,Finland,FIN,100.0,99.999997,99.447946
68,France,FRA,100.0,99.999997,98.644376
69,French Polynesia,PYF,100.0,100.000000,97.509890
70,Gabon,GAB,94.1,88.599501,57.401503
71,"Gambia, The",GMB,66.9,87.103480,48.171144
72,Georgia,GEO,100.0,97.290017,90.680686
73,Germany,DEU,100.0,100.000000,99.226953
74,Ghana,GHA,89.5,89.922012,31.578940
75,Gibraltar,GIB,100.0,100.000000,100.000000
76,Greece,GRC,100.0,100.000000,99.007263
77,Greenland,GRL,100.0,100.000000,NaN
78,Grenada,GRD,94.4,NaN,92.619240
79,Guam,GUM,100.0,99.529301,90.376579
80,Guatemala,GTM,100.0,93.184537,71.169695
81,Guinea,GIN,51.1,74.192484,32.649637
82,Guinea-Bissau,GNB,40.5,61.807703,28.941601
83,Guyana,GUY,98.9,95.644264,91.308722
84,Haiti,HTI,51.3,73.315750,29.108119
85,Honduras,HND,95.6,95.729372,87.671791
86,"Hong Kong SAR, China",HKG,100.0,100.000000,94.834373
87,Hungary,HUN,100.0,100.000000,97.973628
88,Iceland,ISL,100.0,100.000000,98.778002
89,India,IND,99.5,95.724737,83.380872
90,Indonesia,IDN,99.4,89.008760,88.203169
91,"Iran, Islamic Rep.",IRN,100.0,97.852064,90.458288
92,Iraq,IRQ,100.0,98.407694,98.504751
93,Ireland,IRL,100.0,97.098034,89.725606
94,Isle of Man,IMN,100.0,100.000000,100.000000
95,Israel,ISR,100.0,99.999999,99.920078
96,Italy,ITA,100.0,99.917034,99.884904
97,Jamaica,JAM,97.7,87.556262,91.626460
98,Japan,JPN,100.0,99.183168,99.943310
99,Jordan,JOR,100.0,99.286109,96.414791
100,Kazakhstan,KAZ,100.0,97.833653,97.944742
101,Kenya,KEN,76.2,65.596597,40.884965
102,Kiribati,KIR,95.9,79.068345,45.173508
103,"Korea, Dem. People's Rep.",PRK,57.5,93.910918,84.818452
104,"Korea, Rep.",KOR,100.0,100.000000,99.729354
105,Kuwait,KWT,100.0,100.000000,100.000000
106,Kyrgyz Republic,KGZ,100.0,94.943059,98.539900
107,Lao PDR,LAO,96.5,95.863579,88.731413
108,Latvia,LVA,100.0,98.772603,92.534614
109,Lebanon,LBN,100.0,92.600000,99.200000
110,Lesotho,LSO,57.3,78.078996,47.891348
111,Liberia,LBR,32.5,78.827835,23.335195
112,Libya,LBY,73.2,96.354544,88.499146
113,Liechtenstein,LIE,100.0,100.000000,99.950000
114,Lithuania,LTU,100.0,99.918203,96.396565
115,Luxembourg,LUX,100.0,100.000000,97.601174
116,"Macao SAR, China",MAC,100.0,100.000000,100.000000
117,Madagascar,MDG,39.4,55.338961,15.367147
118,Malawi,MWI,15.6,73.053574,49.232209
119,Malaysia,MYS,100.0,97.942466,96.019999
120,Maldives,MDV,100.0,99.758478,99.701302
121,Mali,MLI,54.5,86.363357,47.756168
122,Malta,MLT,100.0,100.000000,100.000000
123,Marshall Islands,MHL,100.0,87.444854,78.958564
124,Mauritania,MRT,50.3,77.284649,58.676920
125,Mauritius,MUS,100.0,99.926546,97.373739
126,Mexico,MEX,99.7,99.541368,92.991282
127,"Micronesia, Fed. Sts.",FSM,86.9,NaN,NaN
128,Moldova,MDA,100.0,92.707916,86.882856
129,Monaco,MCO,100.0,100.000000,100.000000
130,Mongolia,MNG,100.0,86.092655,74.280650
131,Montenegro,MNE,100.0,99.280138,97.849127
132,Morocco,MAR,100.0,92.212027,87.778021
133,Mozambique,MOZ,36.0,66.625244,38.590080
134,Myanmar,MMR,76.8,85.687142,74.183521
135,Namibia,NAM,56.7,86.508738,38.722902
136,Nauru,NRU,100.0,97.842962,71.321135
137,Nepal,NPL,94.0,93.640125,86.025981
138,Netherlands,NLD,100.0,100.000000,97.656669
139,New Caledonia,NCL,100.0,99.538673,100.000000
140,New Zealand,NZL,100.0,100.000000,100.000000
141,Nicaragua,NIC,88.3,NaN,NaN
142,Niger,NER,20.1,53.427466,16.336048
143,Nigeria,NGA,61.2,82.248894,47.901937
144,North Macedonia,MKD,100.0,98.187331,98.997587
145,Northern Mariana Islands,MNP,100.0,100.000000,99.758579
146,Norway,NOR,100.0,100.000000,98.047050
147,Oman,OMN,100.0,92.670219,99.320933
148,Pakistan,PAK,95.6,90.693299,71.882860
149,Palau,PLW,100.0,99.532247,99.024868
150,Panama,PAN,97.0,95.262824,89.054040
151,Papua New Guinea,PNG,20.5,53.298485,23.574339
152,Paraguay,PRY,99.8,99.603596,95.934759
153,Peru,PER,96.2,95.637082,78.773204
154,Philippines,PHL,98.0,95.859221,87.152740
155,Poland,POL,100.0,90.124463,98.956173
156,Portugal,PRT,100.0,99.287612,99.659182
157,Puerto Rico (US),PRI,100.0,100.000000,100.000000
158,Qatar,QAT,100.0,99.988972,99.936545
159,Romania,ROU,100.0,99.999999,90.541361
160,Russian Federation,RUS,100.0,96.900262,92.217588
161,Rwanda,RWA,63.9,61.392176,81.330732
162,Samoa,WSM,100.0,99.440929,97.099104
163,San Marino,SMR,100.0,99.999996,100.000000
164,Sao Tome and Principe,STP,81.3,77.957446,48.678505
165,Saudi Arabia,SAU,100.0,99.040782,97.607498
166,Senegal,SEN,74.2,88.043567,62.519595
167,Serbia,SRB,100.0,95.398382,97.942298
168,Seychelles,SYC,100.0,97.727329,99.700000
169,Sierra Leone,SLE,35.5,68.079024,24.913636
170,Singapore,SGP,100.0,100.000000,100.000000
171,Sint Maarten (Dutch part),SXM,100.0,NaN,NaN
172,Slovak Republic,SVK,100.0,99.786072,97.542960
173,Slovenia,SVN,100.0,99.574594,98.311158
174,Solomon Islands,SLB,81.3,71.609032,34.649074
175,"Somalia, Fed. Rep.",SOM,50.3,75.294796,44.456844
176,South Africa,ZAF,87.7,90.191680,77.384521
177,South Sudan,SSD,5.4,39.749439,14.428240
178,Spain,ESP,100.0,99.924700,99.918119
179,Sri Lanka,LKA,100.0,90.213844,95.353021
180,St. Kitts and Nevis,KNA,100.0,NaN,NaN
181,St. Lucia,LCA,100.0,98.095682,NaN
182,St. Martin (French part),MAF,100.0,99.922938,100.000000
183,St. Vincent and the Grenadines,VCT,100.0,NaN,NaN
184,Sudan,SDN,66.0,64.891713,65.708597
185,Suriname,SUR,99.6,97.997849,89.998275
186,Sweden,SWE,100.0,99.760797,98.743188
187,Switzerland,CHE,100.0,99.999997,99.899871
188,Syrian Arab Republic,SYR,88.4,94.125994,95.648432
189,Tajikistan,TJK,100.0,89.191475,95.985704
190,Tanzania,TZA,48.3,64.605962,37.219361
191,Thailand,THA,100.0,100.000000,99.350488
192,Timor-Leste,TLS,100.0,87.329651,72.935802
193,Togo,TGO,59.2,64.786246,25.168106
194,Tonga,TON,100.0,98.858347,93.933454
195,Trinidad and Tobago,TTO,98.7,99.250308,94.178068
196,Tunisia,TUN,100.0,96.732787,98.537341
197,Turkiye,TUR,100.0,95.986626,99.277702
198,Turkmenistan,TKM,100.0,99.921955,99.735449
199,Turks and Caicos Islands,TCA,100.0,98.832338,93.152600
200,Tuvalu,TUV,100.0,98.741540,89.674451
201,Uganda,UGA,51.5,63.005802,23.896387
202,Ukraine,UKR,100.0,93.479092,97.725826
203,United Arab Emirates,ARE,100.0,100.000000,99.086878
204,United Kingdom,GBR,100.0,99.999999,99.102661
205,United States,USA,100.0,99.980444,99.618273
206,Uruguay,URY,100.0,99.632691,99.150792
207,Uzbekistan,UZB,100.0,97.290487,96.547826
208,Vanuatu,VUT,61.6,87.120061,47.814151
209,"Venezuela, RB",VEN,100.0,93.331611,98.395586
210,Viet Nam,VNM,99.8,98.761247,95.447027
211,Virgin Islands (U.S.),VIR,100.0,99.465680,99.258882
212,West Bank and Gaza,PSE,100.0,98.771707,99.395017
213,"Yemen, Rep.",YEM,83.6,75.035762,63.082731
214,Zambia,ZMB,51.1,73.412038,37.476336
215,Zimbabwe,ZWE,62.0,67.211021,34.641499

### Environment

In [302]:
environment_selected = environmental_data[['Country Name', 'Country Code', 'Series Name', '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]']].copy()

environment_selected = environment_selected[
    environment_selected['Series Name'].isin([
        'Forest area (% of land area)',
        'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)',
        'Renewable energy consumption (% of total final energy consumption)'
    ])
].copy()

# Convert values to numeric
environment_selected['2020 [YR2020]'] = pd.to_numeric(environment_selected['2020 [YR2020]'], errors='coerce')
environment_selected['2021 [YR2021]'] = pd.to_numeric(environment_selected['2021 [YR2021]'], errors='coerce')
environment_selected['2022 [YR2022]'] = pd.to_numeric(environment_selected['2022 [YR2022]'], errors='coerce')
environment_selected['2023 [YR2023]'] = pd.to_numeric(environment_selected['2023 [YR2023]'], errors='coerce')

# Create selected value column
environment_selected['selected_value'] = np.nan

# Forest area: use 2023 first, if missing use 2022
forest_mask = environment_selected['Series Name'] == 'Forest area (% of land area)'
environment_selected.loc[forest_mask, 'selected_value'] = (
    environment_selected.loc[forest_mask, '2023 [YR2023]']
    .fillna(environment_selected.loc[forest_mask, '2022 [YR2022]'])
)

# PM2.5: use 2020 because only 2020 data is available for most countries.
pm25_mask = environment_selected['Series Name'] == 'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)'
environment_selected.loc[pm25_mask, 'selected_value'] = environment_selected.loc[pm25_mask, '2020 [YR2020]']

# Renewable energy: use 2022 first, if missing use 2021
renewable_mask = environment_selected['Series Name'] == 'Renewable energy consumption (% of total final energy consumption)'
environment_selected.loc[renewable_mask, 'selected_value'] = (
    environment_selected.loc[renewable_mask, '2022 [YR2022]']
    .fillna(environment_selected.loc[renewable_mask, '2021 [YR2021]'])
)

environment_final = environment_selected.pivot_table(
    index=['Country Name', 'Country Code'],
    columns='Series Name',
    values='selected_value',
    aggfunc='first'
).reset_index()

environment_final = environment_final.rename(columns={
    'Country Name': 'Country',
    'Forest area (% of land area)': 'forest_area_2023_reference',
    'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)': 'pm2.5_exposure_2020',
    'Renewable energy consumption (% of total final energy consumption)': 'renewable_energy_recent'
})

environment_final.columns.name = None

print(environment_final.shape)
environment_final.head(215)

(215, 5)

,Country,Country Code,forest_area_2023_reference,pm2.5_exposure_2020,renewable_energy_recent
0,Afghanistan,AFG,1.852782,46.087094,20.0
1,Albania,ALB,28.791971,15.707004,41.9
2,Algeria,DZA,0.830314,25.552656,0.1
3,American Samoa,ASM,85.200000,6.715147,0.4
4,Andorra,AND,34.042553,9.080281,18.7
5,Angola,AGO,52.091270,25.145238,52.9
6,Antigua and Barbuda,ATG,18.013409,19.698270,0.9
7,Argentina,ARG,10.321295,14.908174,9.2
8,Armenia,ARM,11.618316,30.579633,9.1
9,Aruba,ABW,2.333333,NaN,8.8
10,Australia,AUS,17.421315,8.251717,12.3
11,Austria,AUT,47.240265,10.933514,36.0
12,Azerbaijan,AZE,14.111954,21.727000,1.3
13,"Bahamas, The",BHS,50.935065,18.939392,1.1
14,Bahrain,BHR,0.950000,58.495063,0.0
15,Bangladesh,BGD,14.489922,42.381376,25.0
16,Barbados,BRB,14.651163,23.730966,5.5
17,Belarus,BLR,43.408069,14.608990,8.2
18,Belgium,BEL,22.604447,11.216066,11.7
19,Belize,BLZ,54.518632,28.651807,30.8
20,Benin,BEN,26.473484,51.047824,54.5
21,Bermuda,BMU,18.518519,7.336001,0.9
22,Bhutan,BTN,71.605139,23.945658,82.5
23,Bolivia,BOL,46.345743,22.879459,12.8
24,Bosnia and Herzegovina,BIH,42.732617,26.601953,36.6
25,Botswana,BWA,26.290826,18.905755,27.4
26,Brazil,BRA,58.981873,12.179325,46.5
27,British Virgin Islands,VGB,24.133333,NaN,1.3
28,Brunei Darussalam,BRN,72.106262,7.597265,0.0
29,Bulgaria,BGR,36.219602,17.147424,20.4
30,Burkina Faso,BFA,22.172515,58.470676,71.4
31,Burundi,BDI,10.889408,29.654135,83.0
32,Cabo Verde,CPV,11.568238,42.322522,21.8
33,Cambodia,KHM,43.061976,24.143602,52.4
34,Cameroon,CMR,42.674113,39.812625,79.2
35,Canada,CAN,39.461712,6.565670,23.8
36,Cayman Islands,CYM,52.472083,NaN,0.0
37,Central African Republic,CAF,35.656040,34.433418,90.9
38,Chad,TCD,3.161031,49.138848,70.0
39,Chile,CHL,25.011646,23.275067,24.2
40,China,CHN,24.031939,34.810524,15.2
41,Colombia,COL,52.766160,14.183251,29.7
42,Comoros,COM,16.980118,11.933272,39.3
43,"Congo, Dem. Rep.",COD,54.189857,26.649483,96.3
44,"Congo, Rep.",COG,64.131772,28.573750,71.4
45,Costa Rica,CRI,60.399138,14.307571,34.2
46,Cote d'Ivoire,CIV,7.855516,49.497783,58.2
47,Croatia,HRV,34.785740,16.120859,34.1
48,Cuba,CUB,31.233141,21.236724,20.9
49,Curacao,CUW,0.157658,NaN,2.8
50,Cyprus,CYP,18.665584,13.508702,15.6
51,Czechia,CZE,34.762388,14.111071,17.2
52,Denmark,DNK,15.781500,9.069839,39.5
53,Djibouti,DJI,0.260725,35.924330,26.9
54,Dominica,DMA,63.826667,20.667300,8.9
55,Dominican Republic,DOM,44.988778,19.826744,14.8
56,Ecuador,ECU,49.545096,16.657021,18.9
57,"Egypt, Arab Rep.",EGY,0.045186,54.858706,6.1
58,El Salvador,SLV,27.527992,20.028714,21.9
59,Equatorial Guinea,GNQ,86.393583,35.379052,4.2
60,Eritrea,ERI,8.630100,32.351521,80.7
61,Estonia,EST,57.065294,6.145733,38.0
62,Eswatini,SWZ,29.138953,18.783121,64.7
63,Ethiopia,ETH,14.930898,27.305328,90.6
64,Faroe Islands,FRO,0.058394,NaN,7.9
65,Fiji,FJI,63.495348,12.418798,28.4
66,Finland,FIN,73.723516,4.895181,50.2
67,France,FRA,32.476482,9.600381,16.2
68,French Polynesia,PYF,43.059637,NaN,7.0
69,Gabon,GAB,91.182365,29.954873,91.3
70,"Gambia, The",GMB,22.279239,58.364040,47.7
71,Georgia,GEO,40.615916,17.043842,25.2
72,Germany,DEU,32.678934,10.287689,17.6
73,Ghana,GHA,35.192196,54.242787,39.0
74,Gibraltar,GIB,0.000000,NaN,0.0
75,Greece,GRC,30.269977,14.408928,21.5
76,Greenland,GRL,0.000536,6.556248,11.7
77,Grenada,GRD,52.058824,24.657242,10.0
78,Guam,GUM,51.851852,9.575106,6.7
79,Guatemala,GTM,32.596118,21.635736,62.1
80,Guinea,GIN,24.698844,43.767445,66.6
81,Guinea-Bissau,GNB,69.512447,50.212766,87.4
82,Guyana,GUY,87.087837,25.460668,12.1
83,Haiti,HTI,12.263062,21.350255,76.7
84,Honduras,HND,56.273215,20.313683,45.9
85,"Hong Kong SAR, China",HKG,NaN,NaN,0.4
86,Hungary,HUN,22.448434,14.136500,15.3
87,Iceland,ISL,0.528744,5.105548,82.4
88,India,IND,24.539030,48.394812,34.9
89,Indonesia,IDN,47.722034,17.881499,20.2
90,"Iran, Islamic Rep.",IRN,6.649236,32.287373,0.9
91,Iraq,IRQ,1.900352,38.175070,1.1
92,Ireland,IRL,11.525911,8.170586,12.7
93,Isle of Man,IMN,6.070175,NaN,2.7
94,Israel,ISR,6.469501,18.598276,6.2
95,Italy,ITA,32.894495,14.658639,17.5
96,Jamaica,JAM,56.190757,17.413637,10.5
97,Japan,JPN,68.395781,12.835202,8.8
98,Jordan,JOR,1.098047,28.773764,11.5
99,Kazakhstan,KAZ,1.312145,20.027872,2.0
100,Kenya,KEN,6.216625,24.391791,67.7
101,Kiribati,KIR,1.456790,11.256827,41.9
102,"Korea, Dem. People's Rep.",PRK,49.550702,29.929106,14.7
103,"Korea, Rep.",KOR,64.108607,25.943990,3.6
104,Kuwait,KWT,0.350730,53.715143,0.1
105,Kyrgyz Republic,KGZ,7.143379,24.381725,27.6
106,Lao PDR,LAO,71.455806,22.317667,49.2
107,Latvia,LVA,54.995983,11.602032,44.0
108,Lebanon,LBN,14.186706,19.231017,6.8
109,Lesotho,LSO,1.137022,23.439101,34.9
110,Liberia,LBR,78.142234,42.361659,92.8
111,Libya,LBY,0.123328,32.970707,3.1
112,Liechtenstein,LIE,41.875000,NaN,56.9
113,Lithuania,LTU,35.230150,9.218939,33.2
114,Luxembourg,LUX,34.453827,8.674762,20.5
115,"Macao SAR, China",MAC,NaN,NaN,11.0
116,Madagascar,MDG,21.296260,12.753520,83.1
117,Malawi,MWI,22.440602,23.698319,62.9
118,Malaysia,MYS,57.719038,16.193853,7.5
119,Maldives,MDV,2.751678,12.012391,1.2
120,Mali,MLI,10.896664,56.783049,71.1
121,Malta,MLT,1.437500,11.722665,8.6
122,Marshall Islands,MHL,52.222222,10.725619,12.2
123,Mauritania,MRT,0.287611,70.822444,19.6
124,Mauritius,MUS,19.474211,9.152969,8.6
125,Mexico,MEX,33.595918,14.992344,13.0
126,"Micronesia, Fed. Sts.",FSM,92.157143,12.114420,2.0
127,Moldova,MDA,11.737018,14.758346,21.4
128,Monaco,MCO,0.000000,9.581070,NaN
129,Mongolia,MNG,9.091724,29.654787,3.0
130,Montenegro,MNE,61.486989,17.982410,39.6
131,Morocco,MAR,12.937107,21.321264,10.9
132,Mozambique,MOZ,45.813035,20.080248,76.9
133,Myanmar,MMR,42.402378,32.315034,62.9
134,Namibia,NAM,7.805111,19.994536,30.0
135,Nauru,NRU,0.000000,6.064355,1.9
136,Nepal,NPL,41.590722,45.720771,73.7
137,Netherlands,NLD,11.057443,10.889250,12.2
138,New Caledonia,NCL,45.827133,NaN,9.6
139,New Zealand,NZL,37.789284,6.485915,28.9
140,Nicaragua,NIC,25.822918,16.809773,50.4
141,Niger,NER,0.822957,85.122346,79.6
142,Nigeria,NGA,23.207890,56.531329,80.3
143,North Macedonia,MKD,39.710151,26.118651,19.5
144,Northern Mariana Islands,MNP,52.956522,9.714631,0.5
145,Norway,NOR,33.500975,6.055897,61.4
146,Oman,OMN,0.007623,39.583577,0.1
147,Pakistan,PAK,4.672426,42.998173,41.6
148,Palau,PLW,90.543478,7.327710,0.9
149,Panama,PAN,56.343973,11.470061,28.0
150,Papua New Guinea,PNG,78.954136,17.310543,54.6
151,Paraguay,PRY,38.544925,10.089160,58.8
152,Peru,PER,56.103020,27.035628,30.6
153,Philippines,PHL,24.460073,20.288742,28.0
154,Poland,POL,31.080419,17.958331,15.2
155,Portugal,PRT,36.154995,8.452423,32.3
156,Puerto Rico (US),PRI,56.121759,7.188415,2.5
157,Qatar,QAT,0.000000,75.663033,0.0
158,Romania,ROU,30.115829,14.850173,23.6
159,Russian Federation,RUS,49.784361,11.272778,3.5
160,Rwanda,RWA,11.309283,31.288265,79.9
161,Samoa,WSM,57.636691,12.551895,35.9
162,San Marino,SMR,16.666667,10.690898,NaN
163,Sao Tome and Principe,STP,52.125000,27.335752,42.5
164,Saudi Arabia,SAU,0.454484,53.148601,0.1
165,Senegal,SEN,41.282709,63.740221,35.4
166,Serbia,SRB,32.389635,22.507536,27.2
167,Seychelles,SYC,73.260870,8.499839,1.9
168,Sierra Leone,SLE,34.298836,43.221094,71.6
169,Singapore,SGP,20.933148,13.869196,1.1
170,Sint Maarten (Dutch part),SXM,10.882353,NaN,0.0
171,Slovak Republic,SVK,40.056156,15.391619,17.9
172,Slovenia,SVN,61.174894,14.291153,23.4
173,Solomon Islands,SLB,90.060021,13.954283,50.1
174,"Somalia, Fed. Rep.",SOM,9.165285,24.525108,95.4
175,South Africa,ZAF,13.965073,23.753069,9.7
176,South Sudan,SSD,11.325622,30.737348,32.4
177,Spain,ESP,37.192589,9.581055,19.0
178,Sri Lanka,LKA,34.004850,19.964441,48.8
179,St. Kitts and Nevis,KNA,42.307692,8.594308,1.5
180,St. Lucia,LCA,34.049180,23.758586,9.7
181,St. Martin (French part),MAF,24.800000,NaN,NaN
182,St. Vincent and the Grenadines,VCT,73.179487,23.926276,5.1
183,Sudan,SDN,9.551965,45.834903,61.0
184,Suriname,SUR,94.447584,27.305970,14.5
185,Sweden,SWE,68.701353,5.636708,57.9
186,Switzerland,CHE,32.382738,9.061050,27.7
187,Syrian Arab Republic,SYR,2.843108,24.705838,1.1
188,Tajikistan,TJK,3.075150,37.053406,34.9
189,Tanzania,TZA,50.054188,25.081431,78.3
190,Thailand,THA,38.687389,31.007202,19.0
191,Timor-Leste,TLS,61.661063,17.410466,11.4
192,Togo,TGO,22.070050,51.666137,75.1
193,Tonga,TON,12.430556,12.478413,2.3
194,Trinidad and Tobago,TTO,44.235867,25.602258,0.5
195,Tunisia,TUN,4.552781,24.182983,11.6
196,Turkiye,TUR,29.479568,21.612047,12.0
197,Turkmenistan,TKM,8.782159,19.599761,0.1
198,Turks and Caicos Islands,TCA,11.073684,NaN,0.8
199,Tuvalu,TUV,33.333333,5.917801,5.2
200,Uganda,UGA,11.041970,33.807719,90.9
201,Ukraine,UKR,16.755264,14.900101,8.9
202,United Arab Emirates,ARE,4.467756,36.305503,1.0
203,United Kingdom,GBR,13.290713,9.912886,12.2
204,United States,USA,33.866926,7.814858,10.9
205,Uruguay,URY,11.964347,10.571792,57.8
206,Uzbekistan,UZB,8.549143,31.960429,1.0
207,Vanuatu,VUT,36.283839,14.082412,25.0
208,"Venezuela, RB",VEN,52.233879,15.256580,33.7
209,Viet Nam,VNM,47.445482,20.801064,24.2
210,Virgin Islands (U.S.),VIR,58.171429,8.633428,5.9
211,West Bank and Gaza,PSE,1.682988,26.363626,15.4
212,"Yemen, Rep.",YEM,1.039832,34.832360,3.7
213,Zambia,ZMB,59.523784,24.308592,83.0
214,Zimbabwe,ZWE,44.736642,19.494180,82.4

### Governance

In [303]:
governance_selected = governance_data[['Country Name', 'Country Code', 'Series Name', '2023 [YR2023]', '2024 [YR2024]']].copy()

governance_selected = governance_selected[
    governance_selected['Series Name'].isin([
        'Government Effectiveness - Governance estimate (approx. -2.5 to +2.5)',
        'Rule of Law - Governance estimate (approx. -2.5 to +2.5)',
        'Political Stability - Governance estimate (approx. -2.5 to +2.5)'
    ])
].copy()

# Convert values to numeric
governance_selected['2023 [YR2023]'] = pd.to_numeric(governance_selected['2023 [YR2023]'], errors='coerce')
governance_selected['2024 [YR2024]'] = pd.to_numeric(governance_selected['2024 [YR2024]'], errors='coerce')
governance_selected['selected_value'] = governance_selected['2024 [YR2024]'].fillna(governance_selected['2023 [YR2023]'])

governance_final = governance_selected.pivot_table(
    index=['Country Name', 'Country Code'],
    columns='Series Name',
    values='selected_value',
    aggfunc='first'
).reset_index()

governance_final = governance_final.rename(columns={
    'Country Name': 'Country',
    'Government Effectiveness - Governance estimate (approx. -2.5 to +2.5)': 'government_effectiveness_2024',
    'Rule of Law - Governance estimate (approx. -2.5 to +2.5)': 'rule_of_law_2024',
    'Political Stability - Governance estimate (approx. -2.5 to +2.5)': 'political_stability_2024'
})

governance_final.columns.name = None

print(governance_final.shape)
governance_final.head()

(215, 5)

,Country,Country Code,government_effectiveness_2024,political_stability_2024,rule_of_law_2024
0,Afghanistan,AFG,-1.933997,-2.205211,-1.935489
1,Albania,ALB,0.312344,0.020467,-0.118502
2,Algeria,DZA,-0.251191,-0.693588,-0.696777
3,American Samoa,ASM,0.767382,1.253029,1.086581
4,Andorra,AND,1.159037,1.543796,1.409905

## 3. Combining the Datasets 
Economic / Environment / Governance / Health & Education / Infrastructure indicators.

After selecting and cleaning the relevant variables from each dataset, the five cleaned datasets were combined into one final dataset. The datasets were stored in a list and merged using the `reduce()` function. `Country` and `Country Code` were used as the common keys for merging.

In [304]:
# Combine datasets

dfs = [economic_final, health_education_final, infrastructure_final, governance_final, environment_final]

merge_dfs = lambda left, right: pd.merge(left, right, on=['Country', 'Country Code'], how='outer')

final_dataset_SLQI = reduce(merge_dfs, dfs)

print(final_dataset_SLQI.shape)
final_dataset_SLQI.head()

(225, 16)

,Country,Country Code,gdp_per_capita_recent,inflation_recent,unemployment_recent,life_expectancy_2024,secondary_enrollment_recent,electricity_access_2024,drinking_water_access,sanitation_access,government_effectiveness_2024,political_stability_2024,rule_of_law_2024,forest_area_2023_reference,pm2.5_exposure_2020,renewable_energy_recent
0,Afghanistan,AFG,413.757895,-6.601186,13.687,66.289,59.613602,85.3,80.832437,54.495799,-1.933997,-2.205211,-1.935489,1.852782,46.087094,20.0
1,Albania,ALB,11377.775743,2.215874,10.689,79.776,108.355392,100.0,95.119427,99.299715,0.312344,0.020467,-0.118502,28.791971,15.707004,41.9
2,Algeria,DZA,5752.990767,4.046115,11.655,76.475,105.164132,100.0,92.420029,85.906486,-0.251191,-0.693588,-0.696777,0.830314,25.552656,0.1
3,American Samoa,ASM,18017.458938,NaN,NaN,72.992,NaN,NaN,100.000000,62.119698,0.767382,1.253029,1.086581,85.200000,6.715147,0.4
4,Andorra,AND,49303.649167,NaN,NaN,84.188,101.923820,100.0,100.000000,100.000000,1.159037,1.543796,1.409905,34.042553,9.080281,18.7

In [305]:
# Rename columns for consistency

final_dataset_SLQI = final_dataset_SLQI.rename(columns={
    'gdp_per_capita_recent': 'gdp_per_capita',
    'inflation_recent': 'inflation',
    'unemployment_recent': 'unemployment_rate',
    
    'life_expectancy_2024': 'life_expectancy',
    'secondary_enrollment_recent': 'secondary_enrollment',
    
    'electricity_access_2024': 'electricity_access',
    
    'government_effectiveness_2024': 'government_effectiveness',
    'political_stability_2024': 'political_stability',
    'rule_of_law_2024': 'rule_of_law',
    
    'forest_area_2023_reference': 'forest_area',
    'pm2.5_exposure_2020': 'pm2.5_exposure',
    'renewable_energy_recent': 'renewable_energy'
})

final_dataset_SLQI.head()

,Country,Country Code,gdp_per_capita,inflation,unemployment_rate,life_expectancy,secondary_enrollment,electricity_access,drinking_water_access,sanitation_access,government_effectiveness,political_stability,rule_of_law,forest_area,pm2.5_exposure,renewable_energy
0,Afghanistan,AFG,413.757895,-6.601186,13.687,66.289,59.613602,85.3,80.832437,54.495799,-1.933997,-2.205211,-1.935489,1.852782,46.087094,20.0
1,Albania,ALB,11377.775743,2.215874,10.689,79.776,108.355392,100.0,95.119427,99.299715,0.312344,0.020467,-0.118502,28.791971,15.707004,41.9
2,Algeria,DZA,5752.990767,4.046115,11.655,76.475,105.164132,100.0,92.420029,85.906486,-0.251191,-0.693588,-0.696777,0.830314,25.552656,0.1
3,American Samoa,ASM,18017.458938,NaN,NaN,72.992,NaN,NaN,100.000000,62.119698,0.767382,1.253029,1.086581,85.200000,6.715147,0.4
4,Andorra,AND,49303.649167,NaN,NaN,84.188,101.923820,100.0,100.000000,100.000000,1.159037,1.543796,1.409905,34.042553,9.080281,18.7

The column names were renamed into a consistent format using short and readable variable names.  
Year labels were removed from the final column names because some indicators used the latest available values rather than only one fixed year.

## 4. Check missing values in final dataset

In [306]:
print("Missing values in final dataset:")
print(final_dataset_SLQI.isnull().sum())

print("\nFinal dataset shape:")
print(final_dataset_SLQI.shape)

Missing values in final dataset:
Country                      0
Country Code                 0
gdp_per_capita              14
inflation                   46
unemployment_rate           38
life_expectancy              8
secondary_enrollment        49
electricity_access          10
drinking_water_access       22
sanitation_access           29
government_effectiveness    12
political_stability         10
rule_of_law                 10
forest_area                 12
pm2.5_exposure              25
renewable_energy            13
dtype: int64

Final dataset shape:
(225, 16)

- Checked missing values in each column
- checked to understand the number of countries and variables after merging.

In [307]:
print("\nData types:")
print(final_dataset_SLQI.dtypes)

Data types:
Country                         str
Country Code                    str
gdp_per_capita              float64
inflation                   float64
unemployment_rate           float64
life_expectancy             float64
secondary_enrollment        float64
electricity_access          float64
drinking_water_access       float64
sanitation_access           float64
government_effectiveness    float64
political_stability         float64
rule_of_law                 float64
forest_area                 float64
pm2.5_exposure              float64
renewable_energy            float64
dtype: object

- checked to make sure that indicator columns were stored as numeric values.

In [308]:
# Count missing values for each country
indicator_columns = final_dataset_SLQI.columns.drop(['Country', 'Country Code'])

final_dataset_SLQI['missing_values_count'] = final_dataset_SLQI[indicator_columns].isnull().sum(axis=1)
final_dataset_SLQI['available_values_count'] = final_dataset_SLQI[indicator_columns].notnull().sum(axis=1)

final_dataset_SLQI[['Country', 'Country Code', 'missing_values_count', 'available_values_count']].head(225)

,Country,Country Code,missing_values_count,available_values_count
0,Afghanistan,AFG,0,14
1,Albania,ALB,0,14
2,Algeria,DZA,0,14
3,American Samoa,ASM,4,10
4,Andorra,AND,2,12
5,Angola,AGO,1,13
6,Anguilla,AIA,11,3
7,Antigua and Barbuda,ATG,1,13
8,Argentina,ARG,2,12
9,Armenia,ARM,0,14
10,Aruba,ABW,4,10
11,Australia,AUS,0,14
12,Austria,AUT,0,14
13,Azerbaijan,AZE,0,14
14,"Bahamas, The",BHS,2,12
15,Bahrain,BHR,0,14
16,Bangladesh,BGD,0,14
17,Barbados,BRB,0,14
18,Belarus,BLR,0,14
19,Belgium,BEL,0,14
20,Belize,BLZ,0,14
21,Benin,BEN,0,14
22,Bermuda,BMU,2,12
23,Bhutan,BTN,0,14
24,Bolivia,BOL,0,14
25,Bosnia and Herzegovina,BIH,1,13
26,Botswana,BWA,0,14
27,Brazil,BRA,0,14
28,British Virgin Islands,VGB,8,6
29,Brunei Darussalam,BRN,0,14
30,Bulgaria,BGR,0,14
31,Burkina Faso,BFA,0,14
32,Burundi,BDI,0,14
33,Cabo Verde,CPV,0,14
34,Cambodia,KHM,0,14
35,Cameroon,CMR,0,14
36,Canada,CAN,0,14
37,Cayman Islands,CYM,3,11
38,Central African Republic,CAF,1,13
39,Chad,TCD,0,14
40,Channel Islands,CHI,10,4
41,Chile,CHL,0,14
42,China,CHN,1,13
43,Colombia,COL,0,14
44,Comoros,COM,0,14
45,"Congo, Dem. Rep.",COD,1,13
46,"Congo, Rep.",COG,3,11
47,Cook Islands,COK,11,3
48,Costa Rica,CRI,0,14
49,Cote d'Ivoire,CIV,0,14
50,Croatia,HRV,1,13
51,Cuba,CUB,1,13
52,Curacao,CUW,7,7
53,Cyprus,CYP,0,14
54,Czechia,CZE,0,14
55,Denmark,DNK,0,14
56,Djibouti,DJI,1,13
57,Dominica,DMA,2,12
58,Dominican Republic,DOM,0,14
59,Ecuador,ECU,0,14
60,"Egypt, Arab Rep.",EGY,0,14
61,El Salvador,SLV,0,14
62,Equatorial Guinea,GNQ,3,11
63,Eritrea,ERI,4,10
64,Estonia,EST,0,14
65,Eswatini,SWZ,2,12
66,Ethiopia,ETH,1,13
67,Faroe Islands,FRO,8,6
68,Fiji,FJI,0,14
69,Finland,FIN,0,14
70,France,FRA,0,14
71,French Guiana,GUF,11,3
72,French Polynesia,PYF,4,10
73,Gabon,GAB,1,13
74,"Gambia, The",GMB,0,14
75,Georgia,GEO,0,14
76,Germany,DEU,0,14
77,Ghana,GHA,0,14
78,Gibraltar,GIB,7,7
79,Greece,GRC,0,14
80,Greenland,GRL,4,10
81,Grenada,GRD,2,12
82,Guam,GUM,2,12
83,Guatemala,GTM,0,14
84,Guinea,GIN,1,13
85,Guinea-Bissau,GNB,1,13
86,Guyana,GUY,0,14
87,Haiti,HTI,1,13
88,Honduras,HND,0,14
89,"Hong Kong SAR, China",HKG,2,12
90,Hungary,HUN,0,14
91,Iceland,ISL,0,14
92,India,IND,0,14
93,Indonesia,IDN,0,14
94,"Iran, Islamic Rep.",IRN,0,14
95,Iraq,IRQ,1,13
96,Ireland,IRL,0,14
97,Isle of Man,IMN,7,7
98,Israel,ISR,0,14
99,Italy,ITA,0,14
100,Jamaica,JAM,0,14
101,Japan,JPN,0,14
102,Jersey,JEY,11,3
103,Jordan,JOR,0,14
104,Kazakhstan,KAZ,0,14
105,Kenya,KEN,0,14
106,Kiribati,KIR,1,13
107,"Korea, Dem. People's Rep.",PRK,3,11
108,"Korea, Rep.",KOR,0,14
109,Kosovo,XKX,8,6
110,Kuwait,KWT,1,13
111,Kyrgyz Republic,KGZ,0,14
112,Lao PDR,LAO,0,14
113,Latvia,LVA,0,14
114,Lebanon,LBN,0,14
115,Lesotho,LSO,1,13
116,Liberia,LBR,0,14
117,Libya,LBY,1,13
118,Liechtenstein,LIE,3,11
119,Lithuania,LTU,0,14
120,Luxembourg,LUX,0,14
121,"Macao SAR, China",MAC,2,12
122,Madagascar,MDG,0,14
123,Malawi,MWI,0,14
124,Malaysia,MYS,0,14
125,Maldives,MDV,0,14
126,Mali,MLI,0,14
127,Malta,MLT,0,14
128,Marshall Islands,MHL,2,12
129,Martinique,MTQ,11,3
130,Mauritania,MRT,0,14
131,Mauritius,MUS,0,14
132,Mexico,MEX,0,14
133,"Micronesia, Fed. Sts.",FSM,4,10
134,Moldova,MDA,0,14
135,Monaco,MCO,3,11
136,Mongolia,MNG,0,14
137,Montenegro,MNE,0,14
138,Morocco,MAR,0,14
139,Mozambique,MOZ,1,13
140,Myanmar,MMR,2,12
141,Namibia,NAM,0,14
142,Nauru,NRU,2,12
143,Nepal,NPL,0,14
144,Netherlands,NLD,0,14
145,New Caledonia,NCL,4,10
146,New Zealand,NZL,0,14
147,Nicaragua,NIC,2,12
148,Niger,NER,0,14
149,Nigeria,NGA,0,14
150,Niue,NIU,11,3
151,North Macedonia,MKD,0,14
152,Northern Mariana Islands,MNP,6,8
153,Norway,NOR,0,14
154,Oman,OMN,0,14
155,Pakistan,PAK,0,14
156,Palau,PLW,1,13
157,Panama,PAN,1,13
158,Papua New Guinea,PNG,0,14
159,Paraguay,PRY,0,14
160,Peru,PER,0,14
161,Philippines,PHL,0,14
162,Poland,POL,0,14
163,Portugal,PRT,0,14
164,Puerto Rico (US),PRI,1,13
165,Qatar,QAT,0,14
166,Reunion,REU,11,3
167,Romania,ROU,0,14
168,Russian Federation,RUS,0,14
169,Rwanda,RWA,0,14
170,Samoa,WSM,1,13
171,San Marino,SMR,2,12
172,Sao Tome and Principe,STP,1,13
173,Saudi Arabia,SAU,0,14
174,Senegal,SEN,0,14
175,Serbia,SRB,0,14
176,Seychelles,SYC,1,13
177,Sierra Leone,SLE,0,14
178,Singapore,SGP,0,14
179,Sint Maarten (Dutch part),SXM,9,5
180,Slovak Republic,SVK,0,14
181,Slovenia,SVN,0,14
182,Solomon Islands,SLB,1,13
183,"Somalia, Fed. Rep.",SOM,1,13
184,South Africa,ZAF,0,14
185,South Sudan,SSD,1,13
186,Spain,ESP,0,14
187,Sri Lanka,LKA,0,14
188,St. Kitts and Nevis,KNA,3,11
189,St. Lucia,LCA,1,13
190,St. Martin (French part),MAF,8,6
191,St. Vincent and the Grenadines,VCT,2,12
192,Sudan,SDN,1,13
193,Suriname,SUR,0,14
194,Sweden,SWE,0,14
195,Switzerland,CHE,0,14
196,Syrian Arab Republic,SYR,1,13
197,"Taiwan, China",TWN,11,3
198,Tajikistan,TJK,1,13
199,Tanzania,TZA,0,14
200,Thailand,THA,0,14
201,Timor-Leste,TLS,0,14
202,Togo,TGO,0,14
203,Tonga,TON,0,14
204,Trinidad and Tobago,TTO,0,14
205,Tunisia,TUN,1,13
206,Turkiye,TUR,0,14
207,Turkmenistan,TKM,1,13
208,Turks and Caicos Islands,TCA,6,8
209,Tuvalu,TUV,2,12
210,Uganda,UGA,1,13
211,Ukraine,UKR,0,14
212,United Arab Emirates,ARE,0,14
213,United Kingdom,GBR,0,14
214,United States,USA,0,14
215,Uruguay,URY,0,14
216,Uzbekistan,UZB,0,14
217,Vanuatu,VUT,0,14
218,"Venezuela, RB",VEN,1,13
219,Viet Nam,VNM,0,14
220,Virgin Islands (U.S.),VIR,2,12
221,West Bank and Gaza,PSE,0,14
222,"Yemen, Rep.",YEM,3,11
223,Zambia,ZMB,0,14
224,Zimbabwe,ZWE,1,13

In [309]:
# Check missing percentage
indicator_columns = final_dataset_SLQI.columns.drop(['Country', 'Country Code', 'missing_values_count', 'available_values_count'],errors='ignore')

# Calculate missing percentage for each variable, will remove it if over 25%.
missing_summary = pd.DataFrame({
    'missing_count': final_dataset_SLQI[indicator_columns].isnull().sum(),
    'missing_percentage': final_dataset_SLQI[indicator_columns].isnull().sum() / len(final_dataset_SLQI) * 100
})

missing_summary = missing_summary.sort_values(by='missing_percentage', ascending=False)
missing_summary

                          missing_count  missing_percentage
secondary_enrollment                 49           21.777778
inflation                            46           20.444444
unemployment_rate                    38           16.888889
sanitation_access                    29           12.888889
pm2.5_exposure                       25           11.111111
drinking_water_access                22            9.777778
gdp_per_capita                       14            6.222222
renewable_energy                     13            5.777778
government_effectiveness             12            5.333333
forest_area                          12            5.333333
electricity_access                   10            4.444444
political_stability                  10            4.444444
rule_of_law                          10            4.444444
life_expectancy                       8            3.555556

- The number and percentage of missing values were calculated for each variable.  It helps to identify which indicators have the most missing data and may need further cleaning or removal.
- Tertiary enrolment was removed because it contained a high number of missing values even after using the latest available data from 2020 to 2024. (70 missing values and over 30%)

In [310]:
# Recalculate missing values for each country
indicator_columns = final_dataset_SLQI.columns.drop(['Country', 'Country Code', 'missing_values_count', 'available_values_count'],errors='ignore')

final_dataset_SLQI['missing_values_count'] = final_dataset_SLQI[indicator_columns].isnull().sum(axis=1)
final_dataset_SLQI['available_values_count'] = final_dataset_SLQI[indicator_columns].notnull().sum(axis=1)

final_dataset_SLQI[['Country', 'Country Code', 'missing_values_count', 'available_values_count']].sort_values(by='missing_values_count', ascending=False).head(100)

,Country,Country Code,missing_values_count,available_values_count
102,Jersey,JEY,11,3
129,Martinique,MTQ,11,3
47,Cook Islands,COK,11,3
197,"Taiwan, China",TWN,11,3
166,Reunion,REU,11,3
150,Niue,NIU,11,3
71,French Guiana,GUF,11,3
6,Anguilla,AIA,11,3
40,Channel Islands,CHI,10,4
179,Sint Maarten (Dutch part),SXM,9,5
109,Kosovo,XKX,8,6
190,St. Martin (French part),MAF,8,6
28,British Virgin Islands,VGB,8,6
67,Faroe Islands,FRO,8,6
52,Curacao,CUW,7,7
78,Gibraltar,GIB,7,7
97,Isle of Man,IMN,7,7
152,Northern Mariana Islands,MNP,6,8
208,Turks and Caicos Islands,TCA,6,8
72,French Polynesia,PYF,4,10
3,American Samoa,ASM,4,10
80,Greenland,GRL,4,10
63,Eritrea,ERI,4,10
133,"Micronesia, Fed. Sts.",FSM,4,10
145,New Caledonia,NCL,4,10
10,Aruba,ABW,4,10
188,St. Kitts and Nevis,KNA,3,11
107,"Korea, Dem. People's Rep.",PRK,3,11
37,Cayman Islands,CYM,3,11
46,"Congo, Rep.",COG,3,11
62,Equatorial Guinea,GNQ,3,11
135,Monaco,MCO,3,11
118,Liechtenstein,LIE,3,11
222,"Yemen, Rep.",YEM,3,11
147,Nicaragua,NIC,2,12
191,St. Vincent and the Grenadines,VCT,2,12
57,Dominica,DMA,2,12
142,Nauru,NRU,2,12
82,Guam,GUM,2,12
89,"Hong Kong SAR, China",HKG,2,12
220,Virgin Islands (U.S.),VIR,2,12
65,Eswatini,SWZ,2,12
171,San Marino,SMR,2,12
14,"Bahamas, The",BHS,2,12
8,Argentina,ARG,2,12
128,Marshall Islands,MHL,2,12
4,Andorra,AND,2,12
140,Myanmar,MMR,2,12
121,"Macao SAR, China",MAC,2,12
22,Bermuda,BMU,2,12
209,Tuvalu,TUV,2,12
81,Grenada,GRD,2,12
73,Gabon,GAB,1,13
182,Solomon Islands,SLB,1,13
95,Iraq,IRQ,1,13
84,Guinea,GIN,1,13
85,Guinea-Bissau,GNB,1,13
176,Seychelles,SYC,1,13
87,Haiti,HTI,1,13
172,Sao Tome and Principe,STP,1,13
170,Samoa,WSM,1,13
164,Puerto Rico (US),PRI,1,13
106,Kiribati,KIR,1,13
110,Kuwait,KWT,1,13
157,Panama,PAN,1,13
115,Lesotho,LSO,1,13
156,Palau,PLW,1,13
117,Libya,LBY,1,13
224,Zimbabwe,ZWE,1,13
183,"Somalia, Fed. Rep.",SOM,1,13
139,Mozambique,MOZ,1,13
7,Antigua and Barbuda,ATG,1,13
38,Central African Republic,CAF,1,13
198,Tajikistan,TJK,1,13
42,China,CHN,1,13
196,Syrian Arab Republic,SYR,1,13
218,"Venezuela, RB",VEN,1,13
45,"Congo, Dem. Rep.",COD,1,13
185,South Sudan,SSD,1,13
51,Cuba,CUB,1,13
50,Croatia,HRV,1,13
192,Sudan,SDN,1,13
5,Angola,AGO,1,13
66,Ethiopia,ETH,1,13
207,Turkmenistan,TKM,1,13
25,Bosnia and Herzegovina,BIH,1,13
205,Tunisia,TUN,1,13
210,Uganda,UGA,1,13
189,St. Lucia,LCA,1,13
56,Djibouti,DJI,1,13
212,United Arab Emirates,ARE,0,14
213,United Kingdom,GBR,0,14
155,Pakistan,PAK,0,14
215,Uruguay,URY,0,14
154,Oman,OMN,0,14
211,Ukraine,UKR,0,14
214,United States,USA,0,14
153,Norway,NOR,0,14
148,Niger,NER,0,14
151,North Macedonia,MKD,0,14

- I also checked missing values at the country level. These countries may need to be removed later if there is not enough data to calculate a reliable index score.

In [311]:
# Remove countries with too many missing values
max_missing_allowed = 4
final_dataset_clean = final_dataset_SLQI[final_dataset_SLQI['missing_values_count'] <= max_missing_allowed].copy()

print(f"Original countries: {len(final_dataset_SLQI)}")
print(f"Countries after cleaning: {len(final_dataset_clean)}")

final_dataset_clean.head(206)

Original countries: 225
Countries after cleaning: 206

,Country,Country Code,gdp_per_capita,inflation,unemployment_rate,life_expectancy,secondary_enrollment,electricity_access,drinking_water_access,sanitation_access,government_effectiveness,political_stability,rule_of_law,forest_area,pm2.5_exposure,renewable_energy,missing_values_count,available_values_count
0,Afghanistan,AFG,413.757895,-6.601186,13.687,66.289000,59.613602,85.3,80.832437,54.495799,-1.933997,-2.205211,-1.935489,1.852782,46.087094,20.0,0,14
1,Albania,ALB,11377.775743,2.215874,10.689,79.776000,108.355392,100.0,95.119427,99.299715,0.312344,0.020467,-0.118502,28.791971,15.707004,41.9,0,14
2,Algeria,DZA,5752.990767,4.046115,11.655,76.475000,105.164132,100.0,92.420029,85.906486,-0.251191,-0.693588,-0.696777,0.830314,25.552656,0.1,0,14
3,American Samoa,ASM,18017.458938,NaN,NaN,72.992000,NaN,NaN,100.000000,62.119698,0.767382,1.253029,1.086581,85.200000,6.715147,0.4,4,10
4,Andorra,AND,49303.649167,NaN,NaN,84.188000,101.923820,100.0,100.000000,100.000000,1.159037,1.543796,1.409905,34.042553,9.080281,18.7,2,12
5,Angola,AGO,2665.874448,28.240495,14.020,64.805000,51.483905,51.1,67.960742,NaN,-0.785191,-0.573596,-1.169741,52.091270,25.145238,52.9,1,13
7,Antigua and Barbuda,ATG,23542.452695,6.198867,NaN,77.766000,108.880779,100.0,98.922727,99.605719,0.429970,1.073149,0.601773,18.013409,19.698270,0.9,1,13
8,Argentina,ARG,13969.783660,219.883929,7.150,77.543000,105.574584,100.0,NaN,NaN,0.183748,-0.169746,-0.251380,10.321295,14.908174,9.2,2,12
9,Armenia,ARM,8556.214070,0.269512,12.405,78.319512,90.945871,100.0,99.931572,93.664943,-0.364029,-0.723297,-0.142394,11.618316,30.579633,9.1,0,14
10,Aruba,ABW,39498.594129,NaN,NaN,76.500000,124.379367,100.0,NaN,98.840002,0.656786,1.330210,1.220060,2.333333,NaN,8.8,4,10
11,Australia,AUS,64603.985631,3.166567,3.942,83.051220,131.931564,100.0,99.969636,100.000000,1.809045,0.793269,1.470401,17.421315,8.251717,12.3,0,14
12,Austria,AUT,58268.878765,2.937916,5.200,81.995122,100.622658,100.0,99.999997,99.972102,1.514511,0.491598,1.677740,47.240265,10.933514,36.0,0,14
13,Azerbaijan,AZE,7283.849908,2.212172,5.648,74.576000,91.122804,100.0,97.688084,98.978507,0.166118,-0.140406,-0.485371,14.111954,21.727000,1.3,0,14
14,"Bahamas, The",BHS,39455.446655,0.409162,9.049,74.710000,79.485875,100.0,NaN,NaN,0.709299,1.049309,0.250995,50.935065,18.939392,1.1,2,12
15,Bahrain,BHR,29653.568273,0.919635,1.084,81.423000,98.813918,100.0,99.919899,100.000000,0.600252,-0.275867,0.167937,0.950000,58.495063,0.0,0,14
16,Bangladesh,BGD,2593.416117,10.465748,3.635,74.930000,64.299719,99.5,98.782542,67.617175,-0.618975,-1.462951,-0.960059,14.489922,42.381376,25.0,0,14
17,Barbados,BRB,26544.870728,1.446437,6.448,76.332000,104.371183,100.0,99.162635,98.092462,0.604570,1.272222,0.727775,14.651163,23.730966,5.5,0,14
18,Belarus,BLR,8317.633999,5.785319,3.458,74.365341,94.790270,100.0,99.892492,99.747353,-0.701546,-0.377300,-1.230600,43.408069,14.608990,8.2,0,14
19,Belgium,BEL,56614.567950,3.143491,5.700,82.300000,142.960266,100.0,100.000000,99.486221,1.194740,0.121453,1.282799,22.604447,11.216066,11.7,0,14
20,Belize,BLZ,7681.244006,3.289560,8.698,73.739000,86.457158,99.6,94.847325,84.301766,-0.129095,0.784722,-0.397150,54.518632,28.651807,30.8,0,14
21,Benin,BEN,1485.380189,1.160931,1.637,60.961000,43.560650,57.0,69.586840,22.248969,-0.185421,-0.403010,-0.412479,26.473484,51.047824,54.5,0,14
22,Bermuda,BMU,142855.374714,NaN,NaN,82.490000,74.396751,100.0,100.000000,99.941653,1.475631,0.971170,0.800106,18.518519,7.336001,0.9,2,12
23,Bhutan,BTN,3831.325355,2.761316,3.282,73.262000,86.181000,100.0,99.546579,86.842108,0.580836,1.354115,0.790266,71.605139,23.945658,82.5,0,14
24,Bolivia,BOL,4421.166099,5.099766,3.274,68.739000,90.527222,99.8,93.387749,71.583920,-0.610417,-0.546036,-1.267722,46.345743,22.879459,12.8,0,14
25,Bosnia and Herzegovina,BIH,9358.787690,1.692127,10.690,78.044000,87.866379,100.0,96.087313,NaN,-0.635316,-0.501061,-0.319134,42.732617,26.601953,36.6,1,13
26,Botswana,BWA,7695.753194,2.818351,23.810,69.293000,70.629257,76.0,91.771364,72.115457,0.416889,1.032294,0.312084,26.290826,18.905755,27.4,0,14
27,Brazil,BRA,10310.548878,4.367464,6.801,76.023000,104.144661,99.8,99.999999,92.401270,-0.224003,-0.520570,-0.446218,58.981873,12.179325,46.5,0,14
29,Brunei Darussalam,BRN,33153.473891,-0.388674,5.180,75.501000,91.838154,100.0,100.000000,100.000000,0.835199,1.202724,0.587608,72.106262,7.597265,0.0,0,14
30,Bulgaria,BGR,17596.017366,2.446519,4.200,75.760976,94.781631,100.0,99.185252,86.076561,0.042820,0.039927,-0.033342,36.219602,17.147424,20.4,0,14
31,Burkina Faso,BFA,981.992650,4.190817,3.441,61.292000,29.990577,21.7,49.998660,31.796349,-0.874867,-1.906331,-0.883859,22.172515,58.470676,71.4,0,14
32,Burundi,BDI,219.424831,20.212493,0.915,63.818000,44.915172,11.6,65.919104,44.633989,-1.006087,-1.376357,-1.302828,10.889408,29.654135,83.0,0,14
33,Cabo Verde,CPV,5192.481573,1.048170,11.883,76.224000,96.431594,98.6,92.280089,83.127922,0.415195,0.769582,0.424201,11.568238,42.322522,21.8,0,14
34,Cambodia,KHM,2627.879698,0.808042,0.254,70.817000,58.789323,95.0,82.849757,83.335933,-0.293501,0.128423,-1.056261,43.061976,24.143602,52.4,0,14
35,Cameroon,CMR,1830.008337,4.533313,3.603,63.968000,44.840796,72.0,71.410179,47.072948,-0.800789,-1.556804,-1.253721,42.674113,39.812625,79.2,0,14
36,Canada,CAN,54340.347722,2.381584,6.351,82.108049,104.320877,100.0,98.290261,98.587883,1.759125,0.598477,1.460830,39.461712,6.565670,23.8,0,14
37,Cayman Islands,CYM,99143.518024,NaN,NaN,80.540000,84.760310,100.0,95.460123,83.244217,1.184250,1.460790,0.830133,52.472083,NaN,0.0,3,11
38,Central African Republic,CAF,516.161000,1.477336,6.253,57.671000,NaN,17.6,36.504027,14.036284,-1.576550,-1.832947,-1.714797,35.656040,34.433418,90.9,1,13
39,Chad,TCD,961.559756,8.899507,1.053,55.238000,23.492989,12.0,52.209053,13.141529,-1.100501,-1.778932,-1.444651,3.161031,49.138848,70.0,0,14
41,Chile,CHL,16709.889397,4.297639,8.718,81.359000,105.608551,100.0,99.081161,99.999996,0.964461,0.121357,0.691055,25.011646,23.275067,24.2,0,14
42,China,CHN,13303.148154,0.218129,4.590,78.017000,NaN,100.0,96.122415,97.271879,0.895784,-0.153336,-0.579320,24.031939,34.810524,15.2,1,13
43,Colombia,COL,7919.208868,6.609086,9.619,77.913000,101.573776,98.7,97.096571,96.582015,-0.111099,-0.970873,-0.559743,52.766160,14.183251,29.7,0,14
44,Comoros,COM,1662.756633,5.051926,3.815,67.023000,54.805729,89.8,85.053928,57.223089,-1.208597,-0.221274,-1.130860,16.980118,11.933272,39.3,0,14
45,"Congo, Dem. Rep.",COD,649.383339,NaN,4.421,62.074000,55.486099,22.1,35.681361,16.303312,-1.693445,-2.119176,-1.626605,54.189857,26.649483,96.3,1,13
46,"Congo, Rep.",COG,2482.248995,3.091436,19.895,66.001000,NaN,51.3,NaN,NaN,-1.110638,-0.258415,-1.178560,64.131772,28.573750,71.4,3,11
48,Costa Rica,CRI,18587.153220,-0.412853,6.936,80.996000,121.810760,100.0,99.815412,98.788841,0.286898,1.175654,0.616741,60.399138,14.307571,34.2,0,14
49,Cote d'Ivoire,CIV,2727.893522,3.450530,2.273,62.110000,65.306506,72.4,77.247059,40.407069,-0.315718,-0.843833,-0.578144,7.855516,49.497783,58.2,0,14
50,Croatia,HRV,24050.439793,2.972005,5.000,78.929268,105.025162,100.0,99.903181,NaN,0.709762,0.581409,0.377484,34.785740,16.120859,34.1,1,13
51,Cuba,CUB,9605.279146,NaN,1.755,78.264000,91.745684,100.0,95.146406,94.770351,-0.269518,0.315527,-0.623572,31.233141,21.236724,20.9,1,13
53,Cyprus,CYP,38674.292969,1.800230,4.900,81.821000,106.741280,100.0,99.721109,99.477676,0.869637,0.385861,0.689191,18.665584,13.508702,15.6,0,14
54,Czechia,CZE,31823.307829,2.435312,2.600,79.978049,97.615417,100.0,98.734148,99.070054,1.177328,0.971901,1.188131,34.762388,14.111071,17.2,0,14
55,Denmark,DNK,71026.483227,1.372200,5.358,82.253659,125.628090,100.0,100.000000,99.597226,1.912899,0.768876,2.004315,15.781500,9.069839,39.5,0,14
56,Djibouti,DJI,3552.723351,2.112012,26.007,66.202000,NaN,65.2,79.661533,67.023484,-0.493044,-0.556359,-1.010399,0.260725,35.924330,26.9,1,13
57,Dominica,DMA,10405.278778,2.569219,NaN,71.294000,102.585808,100.0,96.995311,NaN,0.149042,1.234164,0.397462,63.826667,20.667300,8.9,2,12
58,Dominican Republic,DOM,10875.661844,3.302233,5.312,73.868000,76.364840,99.6,97.457130,90.119824,0.074649,0.589340,-0.182263,44.988778,19.826744,14.8,0,14
59,Ecuador,ECU,6874.705740,1.547325,3.453,77.579000,92.811803,98.7,92.070871,91.204340,-0.219613,-0.721091,-0.965037,49.545096,16.657021,18.9,0,14
60,"Egypt, Arab Rep.",EGY,3338.473714,28.270590,6.817,71.806000,84.828603,100.0,97.298243,97.086129,-0.097058,-0.977923,-0.751540,0.045186,54.858706,6.1,0,14
61,El Salvador,SLV,5579.659692,0.853782,3.261,72.302000,62.142585,98.3,91.619993,88.041116,-0.183179,0.006133,-0.713359,27.527992,20.028714,21.9,0,14
62,Equatorial Guinea,GNQ,6745.400132,2.921402,8.293,63.906000,NaN,66.9,NaN,NaN,-1.182512,-0.140937,-1.540358,86.393583,35.379052,4.2,3,11
63,Eritrea,ERI,NaN,NaN,5.947,68.893000,44.044128,54.4,NaN,NaN,-1.456179,-0.708615,-1.802629,8.630100,32.351521,80.7,4,10
64,Estonia,EST,31428.354782,3.519412,7.600,79.295122,108.538727,100.0,99.999997,99.021494,1.296991,0.699576,1.486448,57.065294,6.145733,38.0,0,14
65,Eswatini,SWZ,3909.558924,NaN,34.643,64.264000,NaN,86.4,80.373711,64.460503,-0.781141,-0.732783,-0.859877,29.138953,18.783121,64.7,2,12
66,Ethiopia,ETH,1133.882797,21.037746,3.357,67.603000,NaN,55.4,55.596070,10.357719,-0.645991,-1.884974,-1.048924,14.930898,27.305328,90.6,1,13
68,Fiji,FJI,6425.741517,3.890842,5.361,67.463000,98.092763,99.3,95.560390,92.754290,0.608961,0.698440,0.305779,63.495348,12.418798,28.4,0,14
69,Finland,FIN,53149.767193,1.565689,8.400,82.336585,142.395157,100.0,99.999997,99.447946,1.817161,0.832569,2.021270,73.723516,4.895181,50.2,0,14
70,France,FRA,46103.084086,1.999049,7.400,82.980488,103.785408,100.0,99.999997,98.644376,1.200701,-0.241365,0.978660,32.476482,9.600381,16.2,0,14
72,French Polynesia,PYF,22439.883875,NaN,11.613,84.192000,NaN,100.0,100.000000,97.509890,NaN,1.030340,1.017195,43.059637,NaN,7.0,4,10
73,Gabon,GAB,8230.043115,1.173120,20.091,68.511000,NaN,94.1,88.599501,57.401503,-0.567155,-0.276887,-1.155705,91.182365,29.954873,91.3,1,13
74,"Gambia, The",GMB,871.340292,11.561053,6.480,66.057000,107.027126,66.9,87.103480,48.171144,-0.535824,-0.018045,-0.394193,22.279239,58.364040,47.7,0,14
75,Georgia,GEO,9241.491223,1.109718,11.557,74.657000,100.959316,100.0,97.290017,90.680686,0.456267,-0.612759,0.148967,40.615916,17.043842,25.2,0,14
76,Germany,DEU,56103.732318,2.256498,3.400,80.792683,100.243698,100.0,100.000000,99.226953,1.546299,0.124267,1.625784,32.678934,10.287689,17.6,0,14
77,Ghana,GHA,2390.772377,22.848328,2.820,65.695000,75.717468,89.5,89.922012,31.578940,0.059580,0.011461,0.053969,35.192196,54.242787,39.0,0,14
79,Greece,GRC,24626.148186,2.741019,10.020,81.839024,105.191742,100.0,100.000000,99.007263,0.191273,0.139420,0.298302,30.269977,14.408928,21.5,0,14
80,Greenland,GRL,58498.970797,NaN,NaN,70.273415,NaN,100.0,100.000000,NaN,1.352849,1.240519,1.574496,0.000536,6.556248,11.7,4,10
81,Grenada,GRD,11705.090298,1.086154,NaN,75.367000,100.731679,94.4,NaN,92.619240,0.020144,1.199264,0.540882,52.058824,24.657242,10.0,2,12
82,Guam,GUM,41833.151713,NaN,5.252,77.422000,NaN,100.0,99.529301,90.376579,1.269394,0.992749,1.034674,51.851852,9.575106,6.7,2,12
83,Guatemala,GTM,6150.025714,2.869928,2.613,72.746000,49.576580,100.0,93.184537,71.169695,-0.909370,-0.209767,-0.962274,32.596118,21.635736,62.1,0,14
84,Guinea,GIN,1694.953759,8.123139,5.132,60.904000,NaN,51.1,74.192484,32.649637,-0.888163,-1.037763,-1.147931,24.698844,43.767445,66.6,1,13
85,Guinea-Bissau,GNB,1007.741517,3.765558,2.647,64.254000,NaN,40.5,61.807703,28.941601,-1.367614,-0.618439,-1.234828,69.512447,50.212766,87.4,1,13
86,Guyana,GUY,29675.244387,2.903952,11.874,70.319000,91.430450,98.9,95.644264,91.308722,-0.098240,0.216498,-0.334222,87.087837,25.460668,12.1,0,14
87,Haiti,HTI,2142.623305,26.949056,14.609,65.119000,NaN,51.3,73.315750,29.108119,-2.015687,-1.201305,-1.603395,12.263062,21.350255,76.7,1,13
88,Honduras,HND,3426.434833,4.606211,4.910,73.044000,51.763981,95.6,95.729372,87.671791,-0.619673,-0.567158,-1.176804,56.273215,20.313683,45.9,0,14
89,"Hong Kong SAR, China",HKG,54074.692852,1.729721,2.988,85.392683,107.160327,100.0,100.000000,94.834373,1.637453,0.631099,0.920980,NaN,NaN,0.4,2,12
90,Hungary,HUN,23292.326388,3.703704,4.500,76.724390,107.350929,100.0,100.000000,97.973628,0.501908,0.436329,0.192336,22.448434,14.136500,15.3,0,14
91,Iceland,ISL,86040.530985,5.856838,3.600,82.809756,108.911362,100.0,100.000000,98.778002,1.645973,1.205603,1.627889,0.528744,5.105548,82.4,0,14
92,India,IND,2694.737809,4.953036,4.173,72.235000,78.105807,99.5,95.724737,83.380872,0.404605,-0.785762,-0.039229,24.539030,48.394812,34.9,0,14
93,Indonesia,IDN,4925.430488,2.181513,3.301,71.288000,98.836444,99.4,89.008760,88.203169,0.179804,-0.609127,-0.206598,47.722034,17.881499,20.2,0,14
94,"Iran, Islamic Rep.",IRN,5190.169590,32.455871,8.146,77.854000,85.146980,100.0,97.852064,90.458288,-0.706123,-1.581188,-1.234801,6.649236,32.287373,0.9,0,14
95,Iraq,IRQ,6073.610323,-12.296984,15.293,72.424000,NaN,100.0,98.407694,98.504751,-1.101885,-2.064276,-1.358161,1.900352,38.175070,1.1,1,13
96,Ireland,IRL,112894.953241,2.113450,4.300,83.009756,130.604965,100.0,97.098034,89.725606,1.611553,0.709970,1.591322,11.525911,8.170586,12.7,0,14
98,Israel,ISR,54176.684438,3.074809,3.595,83.197561,98.547340,100.0,99.999999,99.920078,1.172624,-1.037501,0.599718,6.469501,18.598276,6.2,0,14
99,Italy,ITA,40385.341396,0.982373,6.500,83.951220,100.678757,100.0,99.917034,99.884904,0.792289,0.308704,0.619204,32.894495,14.658639,17.5,0,14
100,Jamaica,JAM,7753.800696,5.411944,3.151,71.606000,84.457237,97.7,87.556262,91.626460,0.171262,0.476823,-0.077670,56.190757,17.413637,10.5,0,14
101,Japan,JPN,32487.077805,2.738537,2.500,84.036341,101.537071,100.0,99.183168,99.943310,2.087910,1.134323,1.511575,68.395781,12.835202,8.8,0,14
103,Jordan,JOR,4618.095925,1.556596,16.693,77.981000,91.751862,100.0,99.286109,96.414791,0.216211,-0.350169,0.168534,1.098047,28.773764,11.5,0,14
104,Kazakhstan,KAZ,14154.632496,8.690822,4.833,74.531000,97.198884,100.0,97.833653,97.944742,0.146764,-0.282756,-0.381548,1.312145,20.027872,2.0,0,14
105,Kenya,KEN,2132.434521,4.489789,5.487,63.834000,84.308388,76.2,65.596597,40.884965,-0.297890,-1.355682,-0.464532,6.216625,24.391791,67.7,0,14
106,Kiribati,KIR,2288.634714,2.455451,NaN,66.600000,90.278671,95.9,79.068345,45.173508,-0.434310,1.238164,0.786010,1.456790,11.256827,41.9,1,13
107,"Korea, Dem. People's Rep.",PRK,NaN,NaN,3.539,73.743000,NaN,57.5,93.910918,84.818452,-1.271310,0.322065,-1.525666,49.550702,29.929106,14.7,3,11
108,"Korea, Rep.",KOR,36238.639908,2.321743,2.784,83.629268,96.253990,100.0,100.000000,99.729354,1.486724,0.639350,1.117455,64.108607,25.943990,3.6,0,14
110,Kuwait,KWT,32717.718663,2.898551,2.151,84.580488,NaN,100.0,100.000000,100.000000,0.327896,0.293937,0.230827,0.350730,53.715143,0.1,1,13
111,Kyrgyz Republic,KGZ,2420.185423,4.997607,3.491,72.400000,91.339996,100.0,94.943059,98.539900,-0.888503,-0.504525,-0.936094,7.143379,24.381725,27.6,0,14
112,Lao PDR,LAO,2123.979094,23.130570,1.174,69.225000,51.852360,96.5,95.863579,88.731413,-0.581901,0.557660,-0.742417,71.455806,22.317667,49.2,0,14
113,Latvia,LVA,23409.084515,1.265799,6.900,76.429268,101.252647,100.0,98.772603,92.534614,0.743180,0.620140,1.091384,54.995983,11.602032,44.0,0,14
114,Lebanon,LBN,3477.724898,45.243042,10.985,77.945000,63.792301,100.0,92.600000,99.200000,-1.130120,-1.389681,-1.085352,14.186706,19.231017,6.8,0,14
115,Lesotho,LSO,971.907718,6.105446,16.340,57.798000,NaN,57.3,78.078996,47.891348,-0.647089,-0.258866,-0.406586,1.137022,23.439101,34.9,1,13
116,Liberia,LBR,851.497724,8.214974,2.914,62.324000,37.741680,32.5,78.827835,23.335195,-1.246293,-0.228549,-0.868004,78.142234,42.361659,92.8,0,14
117,Libya,LBY,6569.164087,2.126158,19.085,71.121000,NaN,73.2,96.354544,88.499146,-1.419488,-1.896477,-1.698013,0.123328,32.970707,3.1,1,13
118,Liechtenstein,LIE,206780.590353,NaN,NaN,84.200000,118.726868,100.0,100.000000,99.950000,1.693164,1.582354,1.727543,41.875000,NaN,56.9,3,11
119,Lithuania,LTU,29384.018960,0.715736,6.851,77.195122,104.860809,100.0,99.918203,96.396565,1.201492,0.939444,1.374236,35.230150,9.218939,33.2,0,14
120,Luxembourg,LUX,137781.681659,2.051133,6.400,83.195122,108.577438,100.0,100.000000,97.601174,2.039714,1.073053,1.761768,34.453827,8.674762,20.5,0,14
121,"Macao SAR, China",MAC,72004.743702,0.672499,2.262,83.331707,94.661677,100.0,100.000000,100.000000,1.115927,1.053872,0.852098,NaN,NaN,11.0,2,12
122,Madagascar,MDG,544.987501,7.613358,3.051,63.835000,34.132036,39.4,55.338961,15.367147,-0.863193,-0.480558,-0.882706,21.296260,12.753520,83.1,0,14
123,Malawi,MWI,522.570394,32.179650,5.051,67.561000,36.644093,15.6,73.053574,49.232209,-0.725760,-0.380208,-0.146300,22.440602,23.698319,62.9,0,14
124,Malaysia,MYS,11874.427368,1.834100,3.846,76.821000,80.275741,100.0,97.942466,96.019999,0.914772,0.384780,0.345136,57.719038,16.193853,7.5,0,14
125,Maldives,MDV,13379.351358,1.399798,4.278,81.285000,79.356530,100.0,99.758478,99.701302,-0.221287,-0.054456,0.044349,2.751678,12.012391,1.2,0,14
126,Mali,MLI,1094.619493,3.206399,2.924,60.675000,38.938947,54.5,86.363357,47.756168,-1.287141,-2.490962,-1.094350,10.896664,56.783049,71.1,0,14
127,Malta,MLT,43898.578181,1.650795,3.100,82.956098,103.027229,100.0,100.000000,100.000000,0.622496,0.804917,0.727180,1.437500,11.722665,8.6,0,14
128,Marshall Islands,MHL,7726.336689,NaN,NaN,67.075000,85.755864,100.0,87.444854,78.958564,-0.290944,1.277219,0.835725,52.222222,10.725619,12.2,2,12
130,Mauritania,MRT,2110.120369,2.491643,10.257,68.713000,36.027703,50.3,77.284649,58.676920,-0.741247,-0.559587,-0.863510,0.287611,70.822444,19.6,0,14
131,Mauritius,MUS,11990.779894,3.604522,5.548,73.789024,90.724659,100.0,99.926546,97.373739,0.765353,0.790352,0.638614,19.474211,9.152969,8.6,0,14
132,Mexico,MEX,14185.781225,4.722256,2.678,75.264000,103.093323,99.7,99.541368,92.991282,-0.219933,-0.715454,-1.153864,33.595918,14.992344,13.0,0,14
133,"Micronesia, Fed. Sts.",FSM,4166.004767,5.408744,NaN,67.357000,NaN,86.9,NaN,NaN,-0.184780,1.499468,0.976941,92.157143,12.114420,2.0,4,10
134,Moldova,MDA,7576.195894,4.677735,1.427,71.332000,99.343917,100.0,92.707916,86.882856,0.257638,-0.344992,-0.161332,11.737018,14.758346,21.4,0,14
135,Monaco,MCO,288001.433369,NaN,NaN,86.497000,158.546616,100.0,100.000000,100.000000,1.737046,1.238708,1.345363,0.000000,9.581070,NaN,3,11
136,Mongolia,MNG,6750.630116,6.197799,5.158,72.398049,96.818120,100.0,86.092655,74.280650,-0.389219,0.420382,-0.099770,9.091724,29.654787,3.0,0,14
137,Montenegro,MNE,13263.328128,3.336750,13.206,77.890244,93.872498,100.0,99.280138,97.849127,0.366495,0.331856,0.181383,61.486989,17.982410,39.6,0,14
138,Morocco,MAR,4153.194336,0.985257,9.103,75.493000,89.983486,100.0,92.212027,87.778021,0.176356,-0.440800,-0.367804,12.937107,21.321264,10.9,0,14
139,Mozambique,MOZ,656.776825,4.078568,6.668,63.797000,NaN,36.0,66.625244,38.590080,-0.715793,-1.758197,-1.194951,45.813035,20.080248,76.9,1,13
140,Myanmar,MMR,1359.050016,NaN,2.887,67.095000,NaN,76.8,85.687142,74.183521,-1.558307,-2.090399,-1.811602,42.402378,32.315034,62.9,2,12
141,Namibia,NAM,4413.127522,4.239039,19.157,67.516000,81.956683,56.7,86.508738,38.722902,0.099343,0.546733,0.327857,7.805111,19.994536,30.0,0,14
142,Nauru,NRU,13609.158838,NaN,NaN,62.279000,91.513352,100.0,97.842962,71.321135,0.010027,1.104705,0.251810,0.000000,6.064355,1.9,2,12
143,Nepal,NPL,1447.310045,4.685097,10.500,70.636000,90.387846,94.0,93.640125,86.025981,-0.884529,-0.414613,-0.303653,41.590722,45.720771,73.7,0,14
144,Netherlands,NLD,67520.421896,3.347543,3.700,81.965854,137.514725,100.0,100.000000,97.656669,1.751997,0.428120,1.706922,11.057443,10.889250,12.2,0,14
145,New Caledonia,NCL,29213.192319,NaN,10.991,78.921000,NaN,100.0,99.538673,100.000000,NaN,1.097620,1.085132,45.827133,NaN,9.6,4,10
146,New Zealand,NZL,49205.179215,2.922798,4.724,82.009756,114.231056,100.0,100.000000,100.000000,1.849185,1.150656,1.667454,37.789284,6.485915,28.9,0,14

- Countries with more than 4 missing indicators were excluded.

## 5. Handle Missing Value

After checking the missing values in the final combined dataset, missing values were handled in two stages.

- First, countries with too many missing indicators were removed because they did not have enough data to calculate a reliable Sustainable Living Quality Index.

- Second, the remaining small number of missing values were filled using median imputation.

In [312]:
print("Missing values after removing countries with too much missing data:")
print(final_dataset_clean.isnull().sum())

Missing values after removing countries with too much missing data:
Country                      0
Country Code                 0
gdp_per_capita               4
inflation                   28
unemployment_rate           20
life_expectancy              0
secondary_enrollment        34
electricity_access           1
drinking_water_access       11
sanitation_access           15
government_effectiveness     2
political_stability          0
rule_of_law                  0
forest_area                  2
pm2.5_exposure               7
renewable_energy             2
missing_values_count         0
available_values_count       0
dtype: int64

In [ ]:
# # Fill remaining missing values with median
indicator_columns = final_dataset_clean.columns.drop( ['Country', 'Country Code', 'missing_values_count', 'available_values_count'],errors='ignore')

for col in indicator_columns:
    final_dataset_clean[col] = final_dataset_clean[col].fillna(
        final_dataset_clean[col].median()
    )

print("Missing values after median imputation:")
print(final_dataset_clean.isnull().sum())

Missing values after median imputation:
Country                     0
Country Code                0
gdp_per_capita              0
inflation                   0
unemployment_rate           0
life_expectancy             0
secondary_enrollment        0
electricity_access          0
drinking_water_access       0
sanitation_access           0
government_effectiveness    0
political_stability         0
rule_of_law                 0
forest_area                 0
pm2.5_exposure              0
renewable_energy            0
dtype: int64

- The remaining small number of missing values were filled using median imputation.

In [321]:
final_dataset_clean = final_dataset_clean.drop(columns=['missing_values_count', 'available_values_count'], errors='ignore')
print(f"Final dataset size: {len(final_dataset_clean)}")
final_dataset_clean.head(206)

Final dataset size: 206

,Country,Country Code,gdp_per_capita,inflation,unemployment_rate,life_expectancy,secondary_enrollment,electricity_access,drinking_water_access,sanitation_access,government_effectiveness,political_stability,rule_of_law,forest_area,pm2.5_exposure,renewable_energy
0,Afghanistan,AFG,413.757895,-6.601186,13.687000,66.289000,59.613602,85.300000,80.832437,54.495799,-1.933997,-2.205211,-1.935489,1.852782,46.087094,20.000000
1,Albania,ALB,11377.775743,2.215874,10.689000,79.776000,108.355392,100.000000,95.119427,99.299715,0.312344,0.020467,-0.118502,28.791971,15.707004,41.900000
2,Algeria,DZA,5752.990767,4.046115,11.655000,76.475000,105.164132,100.000000,92.420029,85.906486,-0.251191,-0.693588,-0.696777,0.830314,25.552656,0.100000
3,American Samoa,ASM,18017.458938,8.805920,6.910833,72.992000,96.812266,92.055568,100.000000,62.119698,0.767382,1.253029,1.086581,85.200000,6.715147,0.400000
4,Andorra,AND,49303.649167,4.342366,5.585877,84.188000,101.923820,100.000000,100.000000,100.000000,1.159037,1.543796,1.409905,34.042553,9.080281,18.700000
5,Angola,AGO,2665.874448,28.240495,14.020000,64.805000,51.483905,51.100000,67.960742,44.070734,-0.785191,-0.573596,-1.169741,52.091270,25.145238,52.900000
7,Antigua and Barbuda,ATG,23542.452695,6.198867,6.691747,77.766000,108.880779,100.000000,98.922727,99.605719,0.429970,1.073149,0.601773,18.013409,19.698270,0.900000
8,Argentina,ARG,13969.783660,219.883929,7.150000,77.543000,105.574584,100.000000,87.780681,101.827827,0.183748,-0.169746,-0.251380,10.321295,14.908174,9.200000
9,Armenia,ARM,8556.214070,0.269512,12.405000,78.319512,90.945871,100.000000,99.931572,93.664943,-0.364029,-0.723297,-0.142394,11.618316,30.579633,9.100000
10,Aruba,ABW,39498.594129,5.743790,6.014615,76.500000,124.379367,100.000000,99.012338,98.840002,0.656786,1.330210,1.220060,2.333333,19.975448,8.800000
11,Australia,AUS,64603.985631,3.166567,3.942000,83.051220,131.931564,100.000000,99.969636,100.000000,1.809045,0.793269,1.470401,17.421315,8.251717,12.300000
12,Austria,AUT,58268.878765,2.937916,5.200000,81.995122,100.622658,100.000000,99.999997,99.972102,1.514511,0.491598,1.677740,47.240265,10.933514,36.000000
13,Azerbaijan,AZE,7283.849908,2.212172,5.648000,74.576000,91.122804,100.000000,97.688084,98.978507,0.166118,-0.140406,-0.485371,14.111954,21.727000,1.300000
14,"Bahamas, The",BHS,39455.446655,0.409162,9.049000,74.710000,79.485875,100.000000,98.785575,92.811675,0.709299,1.049309,0.250995,50.935065,18.939392,1.100000
15,Bahrain,BHR,29653.568273,0.919635,1.084000,81.423000,98.813918,100.000000,99.919899,100.000000,0.600252,-0.275867,0.167937,0.950000,58.495063,0.000000
16,Bangladesh,BGD,2593.416117,10.465748,3.635000,74.930000,64.299719,99.500000,98.782542,67.617175,-0.618975,-1.462951,-0.960059,14.489922,42.381376,25.000000
17,Barbados,BRB,26544.870728,1.446437,6.448000,76.332000,104.371183,100.000000,99.162635,98.092462,0.604570,1.272222,0.727775,14.651163,23.730966,5.500000
18,Belarus,BLR,8317.633999,5.785319,3.458000,74.365341,94.790270,100.000000,99.892492,99.747353,-0.701546,-0.377300,-1.230600,43.408069,14.608990,8.200000
19,Belgium,BEL,56614.567950,3.143491,5.700000,82.300000,142.960266,100.000000,100.000000,99.486221,1.194740,0.121453,1.282799,22.604447,11.216066,11.700000
20,Belize,BLZ,7681.244006,3.289560,8.698000,73.739000,86.457158,99.600000,94.847325,84.301766,-0.129095,0.784722,-0.397150,54.518632,28.651807,30.800000
21,Benin,BEN,1485.380189,1.160931,1.637000,60.961000,43.560650,57.000000,69.586840,22.248969,-0.185421,-0.403010,-0.412479,26.473484,51.047824,54.500000
22,Bermuda,BMU,142855.374714,-9.009496,1.589580,82.490000,74.396751,100.000000,100.000000,99.941653,1.475631,0.971170,0.800106,18.518519,7.336001,0.900000
23,Bhutan,BTN,3831.325355,2.761316,3.282000,73.262000,86.181000,100.000000,99.546579,86.842108,0.580836,1.354115,0.790266,71.605139,23.945658,82.500000
24,Bolivia,BOL,4421.166099,5.099766,3.274000,68.739000,90.527222,99.800000,93.387749,71.583920,-0.610417,-0.546036,-1.267722,46.345743,22.879459,12.800000
25,Bosnia and Herzegovina,BIH,9358.787690,1.692127,10.690000,78.044000,87.866379,100.000000,96.087313,91.225587,-0.635316,-0.501061,-0.319134,42.732617,26.601953,36.600000
26,Botswana,BWA,7695.753194,2.818351,23.810000,69.293000,70.629257,76.000000,91.771364,72.115457,0.416889,1.032294,0.312084,26.290826,18.905755,27.400000
27,Brazil,BRA,10310.548878,4.367464,6.801000,76.023000,104.144661,99.800000,99.999999,92.401270,-0.224003,-0.520570,-0.446218,58.981873,12.179325,46.500000
29,Brunei Darussalam,BRN,33153.473891,-0.388674,5.180000,75.501000,91.838154,100.000000,100.000000,100.000000,0.835199,1.202724,0.587608,72.106262,7.597265,0.000000
30,Bulgaria,BGR,17596.017366,2.446519,4.200000,75.760976,94.781631,100.000000,99.185252,86.076561,0.042820,0.039927,-0.033342,36.219602,17.147424,20.400000
31,Burkina Faso,BFA,981.992650,4.190817,3.441000,61.292000,29.990577,21.700000,49.998660,31.796349,-0.874867,-1.906331,-0.883859,22.172515,58.470676,71.400000
32,Burundi,BDI,219.424831,20.212493,0.915000,63.818000,44.915172,11.600000,65.919104,44.633989,-1.006087,-1.376357,-1.302828,10.889408,29.654135,83.000000
33,Cabo Verde,CPV,5192.481573,1.048170,11.883000,76.224000,96.431594,98.600000,92.280089,83.127922,0.415195,0.769582,0.424201,11.568238,42.322522,21.800000
34,Cambodia,KHM,2627.879698,0.808042,0.254000,70.817000,58.789323,95.000000,82.849757,83.335933,-0.293501,0.128423,-1.056261,43.061976,24.143602,52.400000
35,Cameroon,CMR,1830.008337,4.533313,3.603000,63.968000,44.840796,72.000000,71.410179,47.072948,-0.800789,-1.556804,-1.253721,42.674113,39.812625,79.200000
36,Canada,CAN,54340.347722,2.381584,6.351000,82.108049,104.320877,100.000000,98.290261,98.587883,1.759125,0.598477,1.460830,39.461712,6.565670,23.800000
37,Cayman Islands,CYM,99143.518024,-2.771814,3.450402,80.540000,84.760310,100.000000,95.460123,83.244217,1.184250,1.460790,0.830133,52.472083,13.768968,0.000000
38,Central African Republic,CAF,516.161000,1.477336,6.253000,57.671000,36.667282,17.600000,36.504027,14.036284,-1.576550,-1.832947,-1.714797,35.656040,34.433418,90.900000
39,Chad,TCD,961.559756,8.899507,1.053000,55.238000,23.492989,12.000000,52.209053,13.141529,-1.100501,-1.778932,-1.444651,3.161031,49.138848,70.000000
41,Chile,CHL,16709.889397,4.297639,8.718000,81.359000,105.608551,100.000000,99.081161,99.999996,0.964461,0.121357,0.691055,25.011646,23.275067,24.200000
42,China,CHN,13303.148154,0.218129,4.590000,78.017000,89.660212,100.000000,96.122415,97.271879,0.895784,-0.153336,-0.579320,24.031939,34.810524,15.200000
43,Colombia,COL,7919.208868,6.609086,9.619000,77.913000,101.573776,98.700000,97.096571,96.582015,-0.111099,-0.970873,-0.559743,52.766160,14.183251,29.700000
44,Comoros,COM,1662.756633,5.051926,3.815000,67.023000,54.805729,89.800000,85.053928,57.223089,-1.208597,-0.221274,-1.130860,16.980118,11.933272,39.300000
45,"Congo, Dem. Rep.",COD,649.383339,11.295277,4.421000,62.074000,55.486099,22.100000,35.681361,16.303312,-1.693445,-2.119176,-1.626605,54.189857,26.649483,96.300000
46,"Congo, Rep.",COG,2482.248995,3.091436,19.895000,66.001000,60.901303,51.300000,72.538559,44.882854,-1.110638,-0.258415,-1.178560,64.131772,28.573750,71.400000
48,Costa Rica,CRI,18587.153220,-0.412853,6.936000,80.996000,121.810760,100.000000,99.815412,98.788841,0.286898,1.175654,0.616741,60.399138,14.307571,34.200000
49,Cote d'Ivoire,CIV,2727.893522,3.450530,2.273000,62.110000,65.306506,72.400000,77.247059,40.407069,-0.315718,-0.843833,-0.578144,7.855516,49.497783,58.200000
50,Croatia,HRV,24050.439793,2.972005,5.000000,78.929268,105.025162,100.000000,99.903181,95.075845,0.709762,0.581409,0.377484,34.785740,16.120859,34.100000
51,Cuba,CUB,9605.279146,10.008568,1.755000,78.264000,91.745684,100.000000,95.146406,94.770351,-0.269518,0.315527,-0.623572,31.233141,21.236724,20.900000
53,Cyprus,CYP,38674.292969,1.800230,4.900000,81.821000,106.741280,100.000000,99.721109,99.477676,0.869637,0.385861,0.689191,18.665584,13.508702,15.600000
54,Czechia,CZE,31823.307829,2.435312,2.600000,79.978049,97.615417,100.000000,98.734148,99.070054,1.177328,0.971901,1.188131,34.762388,14.111071,17.200000
55,Denmark,DNK,71026.483227,1.372200,5.358000,82.253659,125.628090,100.000000,100.000000,99.597226,1.912899,0.768876,2.004315,15.781500,9.069839,39.500000
56,Djibouti,DJI,3552.723351,2.112012,26.007000,66.202000,72.347010,65.200000,79.661533,67.023484,-0.493044,-0.556359,-1.010399,0.260725,35.924330,26.900000
57,Dominica,DMA,10405.278778,2.569219,7.240629,71.294000,102.585808,100.000000,96.995311,86.709391,0.149042,1.234164,0.397462,63.826667,20.667300,8.900000
58,Dominican Republic,DOM,10875.661844,3.302233,5.312000,73.868000,76.364840,99.600000,97.457130,90.119824,0.074649,0.589340,-0.182263,44.988778,19.826744,14.800000
59,Ecuador,ECU,6874.705740,1.547325,3.453000,77.579000,92.811803,98.700000,92.070871,91.204340,-0.219613,-0.721091,-0.965037,49.545096,16.657021,18.900000
60,"Egypt, Arab Rep.",EGY,3338.473714,28.270590,6.817000,71.806000,84.828603,100.000000,97.298243,97.086129,-0.097058,-0.977923,-0.751540,0.045186,54.858706,6.100000
61,El Salvador,SLV,5579.659692,0.853782,3.261000,72.302000,62.142585,98.300000,91.619993,88.041116,-0.183179,0.006133,-0.713359,27.527992,20.028714,21.900000
62,Equatorial Guinea,GNQ,6745.400132,2.921402,8.293000,63.906000,76.790559,66.900000,83.270178,59.370848,-1.182512,-0.140937,-1.540358,86.393583,35.379052,4.200000
63,Eritrea,ERI,13675.292623,9.434109,5.947000,68.893000,44.044128,54.400000,70.954339,47.454998,-1.456179,-0.708615,-1.802629,8.630100,32.351521,80.700000
64,Estonia,EST,31428.354782,3.519412,7.600000,79.295122,108.538727,100.000000,99.999997,99.021494,1.296991,0.699576,1.486448,57.065294,6.145733,38.000000
65,Eswatini,SWZ,3909.558924,10.824764,34.643000,64.264000,76.441539,86.400000,80.373711,64.460503,-0.781141,-0.732783,-0.859877,29.138953,18.783121,64.700000
66,Ethiopia,ETH,1133.882797,21.037746,3.357000,67.603000,51.977550,55.400000,55.596070,10.357719,-0.645991,-1.884974,-1.048924,14.930898,27.305328,90.600000
68,Fiji,FJI,6425.741517,3.890842,5.361000,67.463000,98.092763,99.300000,95.560390,92.754290,0.608961,0.698440,0.305779,63.495348,12.418798,28.400000
69,Finland,FIN,53149.767193,1.565689,8.400000,82.336585,142.395157,100.000000,99.999997,99.447946,1.817161,0.832569,2.021270,73.723516,4.895181,50.200000
70,France,FRA,46103.084086,1.999049,7.400000,82.980488,103.785408,100.000000,99.999997,98.644376,1.200701,-0.241365,0.978660,32.476482,9.600381,16.200000
72,French Polynesia,PYF,22439.883875,8.175728,11.613000,84.192000,101.145086,100.000000,100.000000,97.509890,0.976457,1.030340,1.017195,43.059637,17.260476,7.000000
73,Gabon,GAB,8230.043115,1.173120,20.091000,68.511000,71.635577,94.100000,88.599501,57.401503,-0.567155,-0.276887,-1.155705,91.182365,29.954873,91.300000
74,"Gambia, The",GMB,871.340292,11.561053,6.480000,66.057000,107.027126,66.900000,87.103480,48.171144,-0.535824,-0.018045,-0.394193,22.279239,58.364040,47.700000
75,Georgia,GEO,9241.491223,1.109718,11.557000,74.657000,100.959316,100.000000,97.290017,90.680686,0.456267,-0.612759,0.148967,40.615916,17.043842,25.200000
76,Germany,DEU,56103.732318,2.256498,3.400000,80.792683,100.243698,100.000000,100.000000,99.226953,1.546299,0.124267,1.625784,32.678934,10.287689,17.600000
77,Ghana,GHA,2390.772377,22.848328,2.820000,65.695000,75.717468,89.500000,89.922012,31.578940,0.059580,0.011461,0.053969,35.192196,54.242787,39.000000
79,Greece,GRC,24626.148186,2.741019,10.020000,81.839024,105.191742,100.000000,100.000000,99.007263,0.191273,0.139420,0.298302,30.269977,14.408928,21.500000
80,Greenland,GRL,58498.970797,3.032097,5.198989,70.273415,104.162928,100.000000,100.000000,89.865416,1.352849,1.240519,1.574496,0.000536,6.556248,11.700000
81,Grenada,GRD,11705.090298,1.086154,7.185948,75.367000,100.731679,94.400000,97.107788,92.619240,0.020144,1.199264,0.540882,52.058824,24.657242,10.000000
82,Guam,GUM,41833.151713,5.407739,5.252000,77.422000,103.922350,100.000000,99.529301,90.376579,1.269394,0.992749,1.034674,51.851852,9.575106,6.700000
83,Guatemala,GTM,6150.025714,2.869928,2.613000,72.746000,49.576580,100.000000,93.184537,71.169695,-0.909370,-0.209767,-0.962274,32.596118,21.635736,62.100000
84,Guinea,GIN,1694.953759,8.123139,5.132000,60.904000,53.776676,51.100000,74.192484,32.649637,-0.888163,-1.037763,-1.147931,24.698844,43.767445,66.600000
85,Guinea-Bissau,GNB,1007.741517,3.765558,2.647000,64.254000,45.348644,40.500000,61.807703,28.941601,-1.367614,-0.618439,-1.234828,69.512447,50.212766,87.400000
86,Guyana,GUY,29675.244387,2.903952,11.874000,70.319000,91.430450,98.900000,95.644264,91.308722,-0.098240,0.216498,-0.334222,87.087837,25.460668,12.100000
87,Haiti,HTI,2142.623305,26.949056,14.609000,65.119000,60.573608,51.300000,73.315750,29.108119,-2.015687,-1.201305,-1.603395,12.263062,21.350255,76.700000
88,Honduras,HND,3426.434833,4.606211,4.910000,73.044000,51.763981,95.600000,95.729372,87.671791,-0.619673,-0.567158,-1.176804,56.273215,20.313683,45.900000
89,"Hong Kong SAR, China",HKG,54074.692852,1.729721,2.988000,85.392683,107.160327,100.000000,100.000000,94.834373,1.637453,0.631099,0.920980,29.103150,17.414921,0.400000
90,Hungary,HUN,23292.326388,3.703704,4.500000,76.724390,107.350929,100.000000,100.000000,97.973628,0.501908,0.436329,0.192336,22.448434,14.136500,15.300000
91,Iceland,ISL,86040.530985,5.856838,3.600000,82.809756,108.911362,100.000000,100.000000,98.778002,1.645973,1.205603,1.627889,0.528744,5.105548,82.400000
92,India,IND,2694.737809,4.953036,4.173000,72.235000,78.105807,99.500000,95.724737,83.380872,0.404605,-0.785762,-0.039229,24.539030,48.394812,34.900000
93,Indonesia,IDN,4925.430488,2.181513,3.301000,71.288000,98.836444,99.400000,89.008760,88.203169,0.179804,-0.609127,-0.206598,47.722034,17.881499,20.200000
94,"Iran, Islamic Rep.",IRN,5190.169590,32.455871,8.146000,77.854000,85.146980,100.000000,97.852064,90.458288,-0.706123,-1.581188,-1.234801,6.649236,32.287373,0.900000
95,Iraq,IRQ,6073.610323,-12.296984,15.293000,72.424000,88.114661,100.000000,98.407694,98.504751,-1.101885,-2.064276,-1.358161,1.900352,38.175070,1.100000
96,Ireland,IRL,112894.953241,2.113450,4.300000,83.009756,130.604965,100.000000,97.098034,89.725606,1.611553,0.709970,1.591322,11.525911,8.170586,12.700000
98,Israel,ISR,54176.684438,3.074809,3.595000,83.197561,98.547340,100.000000,99.999999,99.920078,1.172624,-1.037501,0.599718,6.469501,18.598276,6.200000
99,Italy,ITA,40385.341396,0.982373,6.500000,83.951220,100.678757,100.000000,99.917034,99.884904,0.792289,0.308704,0.619204,32.894495,14.658639,17.500000
100,Jamaica,JAM,7753.800696,5.411944,3.151000,71.606000,84.457237,97.700000,87.556262,91.626460,0.171262,0.476823,-0.077670,56.190757,17.413637,10.500000
101,Japan,JPN,32487.077805,2.738537,2.500000,84.036341,101.537071,100.000000,99.183168,99.943310,2.087910,1.134323,1.511575,68.395781,12.835202,8.800000
103,Jordan,JOR,4618.095925,1.556596,16.693000,77.981000,91.751862,100.000000,99.286109,96.414791,0.216211,-0.350169,0.168534,1.098047,28.773764,11.500000
104,Kazakhstan,KAZ,14154.632496,8.690822,4.833000,74.531000,97.198884,100.000000,97.833653,97.944742,0.146764,-0.282756,-0.381548,1.312145,20.027872,2.000000
105,Kenya,KEN,2132.434521,4.489789,5.487000,63.834000,84.308388,76.200000,65.596597,40.884965,-0.297890,-1.355682,-0.464532,6.216625,24.391791,67.700000
106,Kiribati,KIR,2288.634714,2.455451,7.581407,66.600000,90.278671,95.900000,79.068345,45.173508,-0.434310,1.238164,0.786010,1.456790,11.256827,41.900000
107,"Korea, Dem. People's Rep.",PRK,25890.859849,7.685443,3.539000,73.743000,83.180920,57.500000,93.910918,84.818452,-1.271310,0.322065,-1.525666,49.550702,29.929106,14.700000
108,"Korea, Rep.",KOR,36238.639908,2.321743,2.784000,83.629268,96.253990,100.000000,100.000000,99.729354,1.486724,0.639350,1.117455,64.108607,25.943990,3.600000
110,Kuwait,KWT,32717.718663,2.898551,2.151000,84.580488,93.345106,100.000000,100.000000,100.000000,0.327896,0.293937,0.230827,0.350730,53.715143,0.100000
111,Kyrgyz Republic,KGZ,2420.185423,4.997607,3.491000,72.400000,91.339996,100.000000,94.943059,98.539900,-0.888503,-0.504525,-0.936094,7.143379,24.381725,27.600000
112,Lao PDR,LAO,2123.979094,23.130570,1.174000,69.225000,51.852360,96.500000,95.863579,88.731413,-0.581901,0.557660,-0.742417,71.455806,22.317667,49.200000
113,Latvia,LVA,23409.084515,1.265799,6.900000,76.429268,101.252647,100.000000,98.772603,92.534614,0.743180,0.620140,1.091384,54.995983,11.602032,44.000000
114,Lebanon,LBN,3477.724898,45.243042,10.985000,77.945000,63.792301,100.000000,92.600000,99.200000,-1.130120,-1.389681,-1.085352,14.186706,19.231017,6.800000
115,Lesotho,LSO,971.907718,6.105446,16.340000,57.798000,67.235889,57.300000,78.078996,47.891348,-0.647089,-0.258866,-0.406586,1.137022,23.439101,34.900000
116,Liberia,LBR,851.497724,8.214974,2.914000,62.324000,37.741680,32.500000,78.827835,23.335195,-1.246293,-0.228549,-0.868004,78.142234,42.361659,92.800000
117,Libya,LBY,6569.164087,2.126158,19.085000,71.121000,83.838067,73.200000,96.354544,88.499146,-1.419488,-1.896477,-1.698013,0.123328,32.970707,3.100000
118,Liechtenstein,LIE,206780.590353,-18.132008,-1.143402,84.200000,118.726868,100.000000,100.000000,99.950000,1.693164,1.582354,1.727543,41.875000,-1.406529,56.900000
119,Lithuania,LTU,29384.018960,0.715736,6.851000,77.195122,104.860809,100.000000,99.918203,96.396565,1.201492,0.939444,1.374236,35.230150,9.218939,33.200000
120,Luxembourg,LUX,137781.681659,2.051133,6.400000,83.195122,108.577438,100.000000,100.000000,97.601174,2.039714,1.073053,1.761768,34.453827,8.674762,20.500000
121,"Macao SAR, China",MAC,72004.743702,0.672499,2.262000,83.331707,94.661677,100.000000,100.000000,100.000000,1.115927,1.053872,0.852098,27.679047,16.876105,11.000000
122,Madagascar,MDG,544.987501,7.613358,3.051000,63.835000,34.132036,39.400000,55.338961,15.367147,-0.863193,-0.480558,-0.882706,21.296260,12.753520,83.100000
123,Malawi,MWI,522.570394,32.179650,5.051000,67.561000,36.644093,15.600000,73.053574,49.232209,-0.725760,-0.380208,-0.146300,22.440602,23.698319,62.900000
124,Malaysia,MYS,11874.427368,1.834100,3.846000,76.821000,80.275741,100.000000,97.942466,96.019999,0.914772,0.384780,0.345136,57.719038,16.193853,7.500000
125,Maldives,MDV,13379.351358,1.399798,4.278000,81.285000,79.356530,100.000000,99.758478,99.701302,-0.221287,-0.054456,0.044349,2.751678,12.012391,1.200000
126,Mali,MLI,1094.619493,3.206399,2.924000,60.675000,38.938947,54.500000,86.363357,47.756168,-1.287141,-2.490962,-1.094350,10.896664,56.783049,71.100000
127,Malta,MLT,43898.578181,1.650795,3.100000,82.956098,103.027229,100.000000,100.000000,100.000000,0.622496,0.804917,0.727180,1.437500,11.722665,8.600000
128,Marshall Islands,MHL,7726.336689,10.276174,7.352577,67.075000,85.755864,100.000000,87.444854,78.958564,-0.290944,1.277219,0.835725,52.222222,10.725619,12.200000
130,Mauritania,MRT,2110.120369,2.491643,10.257000,68.713000,36.027703,50.300000,77.284649,58.676920,-0.741247,-0.559587,-0.863510,0.287611,70.822444,19.600000
131,Mauritius,MUS,11990.779894,3.604522,5.548000,73.789024,90.724659,100.000000,99.926546,97.373739,0.765353,0.790352,0.638614,19.474211,9.152969,8.600000
132,Mexico,MEX,14185.781225,4.722256,2.678000,75.264000,103.093323,99.700000,99.541368,92.991282,-0.219933,-0.715454,-1.153864,33.595918,14.992344,13.000000
133,"Micronesia, Fed. Sts.",FSM,4166.004767,5.408744,7.499611,67.357000,90.516941,86.900000,91.843001,75.980922,-0.184780,1.499468,0.976941,92.157143,12.114420,2.000000
134,Moldova,MDA,7576.195894,4.677735,1.427000,71.332000,99.343917,100.000000,92.707916,86.882856,0.257638,-0.344992,-0.161332,11.737018,14.758346,21.400000
135,Monaco,MCO,288001.433369,-29.721717,-4.592894,86.497000,158.546616,100.000000,100.000000,100.000000,1.737046,1.238708,1.345363,0.000000,9.581070,22.887325
136,Mongolia,MNG,6750.630116,6.197799,5.158000,72.398049,96.818120,100.000000,86.092655,74.280650,-0.389219,0.420382,-0.099770,9.091724,29.654787,3.000000